### ISSUE TITLE
Conflicting with TTFR-1.11.2-1.7.3. Removing/disabling TTFR-1.11.2-1.7.3 temporarily allows /profile [chunks] [all] to succesfull output without a hang, can just re-enable it later, #minor, #workaround

### ISSUE THREAD

**Issue by numinari** [way2muchnoise/JustEnoughResources#114]
tested with both default san serif and also Kristen ITC >>> this is copped from https://github.com/cubex2/BetterFonts/issues/13 > I did a thorough source of cubex2/BetterFonts maybe there's a conflicting use of java.lang output code somewhere? I couldn't find any reason JEI should be reloading.

The only time I can get the crash is with

TTFR-1.11.2-1.7.3
jei_1.11.2-4.3.5.274
JustEnoughResources-1.11.2-0.6.3.5
On Forge 1.11.2-13.20.0.2296

I ran the just enough resources /profile 100 all command with only JEI and JER, it completed and output to files successfully. I then installed betterfonts and ran the command again, and the server hung, I had to kill the process. Removing betterfonts removes the conflict, so I assumed the issue was in betterfonts.

Either JER tries outputting in truetype or something weird (why would it use the minecraft font and not the system default?) or when the /profile command tries to complete betterfonts attempts to reload JEI for some reason and hangs the server.

Anyway I would appreciate if you could look into this a bit more? It's able to be worked around by simply disabling better fonts, running the command, than re-enabling. No big deal. :D

#workaround #minor

It is possible this isn't your code and it's the Just Enough Resources code. I haven't looked into anything further than the test described here. I don't mind cross posting this to JER if you deem it necessary.

Thanks!

## **update** I have to say I looked through BetterFonts (TTFR-1.11.2-1.7.3) java source and didn't see anything I understood to be conflicting. I'll go ahead and report this over on JER's site just in-case someone more familiar with the java.lang over here also knows what might be happening.

full log follows
https://paste.ee/p/XWxkm

[01:00:19] [Thread-22/INFO] [FML]: Loading dimension -1 (hrk) (net.minecraft.server.integrated.IntegratedServer@15867f66)
[01:00:20] [Client thread/INFO]: [CHAT] [Nether] Started profiling
[01:00:21] [Thread-22/INFO] [FML]: Loading dimension 1 (hrk) (net.minecraft.server.integrated.IntegratedServer@15867f66)
[01:00:22] [Client thread/INFO]: [CHAT] [The End] Started profiling
[01:00:22] [Thread-22/INFO] [FML]: Loading dimension 0 (hrk) (net.minecraft.server.integrated.IntegratedServer@15867f66)
[01:00:24] [Client thread/INFO]: [CHAT] [Overworld] Started profiling
[01:00:26] [Thread-22/ERROR] [jei]: A mod tried to reload JEI, this is no longer supported. See the javadocs for more information
java.lang.RuntimeException
	at mezz.jei.runtime.JeiHelpers.reload(JeiHelpers.java:52) [JeiHelpers.class:?]
	at jeresources.profiling.Profiler.run(Profiler.java:47) [Profiler.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[01:00:34] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4430ms behind, skipping 88 tick(s)
Process was killed by user.

**Comment by way2muchnoise** [comment]
Reloading was removed in JEI, the reloading is commented out as of 890343b843693b81891e47c837be868d4facbe65. Will be backported soon.
