### ISSUE TITLE
IllegalArgumentException during profiling

### ISSUE THREAD

**Issue by brennie** [way2muchnoise/JustEnoughResources#141]
Running `/profile 100 all` results in the following output in the log:

```
[03:51:13] [Thread-160/INFO] [FML]: Loading dimension -9999 (New TEST) (net.minecraft.server.integrated.IntegratedServer@10396e05)
[03:51:13] [Thread-160/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.IllegalArgumentException: Could not get provider type for dimension -11, does not exist
[03:51:13] [Thread-160/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:146)
[03:51:13] [Thread-160/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:296)
[03:51:13] [Thread-160/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.world.WorldServer.<init>(WorldServer.java:110)
[03:51:13] [Thread-160/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at jeresources.profiling.DummyWorld.<init>(DummyWorld.java:36)
[03:51:13] [Thread-160/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at jeresources.profiling.Profiler.profileWorld(Profiler.java:54)
[03:51:13] [Thread-160/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at jeresources.profiling.Profiler.run(Profiler.java:39)
[03:51:13] [Thread-160/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Thread.run(Unknown Source)
```

I'm also getting a bunch of exceptions about missing recipes for things in the advancement manager, but I have no idea if that's related.

**Comment by way2muchnoise** [comment]
What version of JER are you running. I thought this was fixed in #138, you could aslo use the blacklist added in #123.

**Comment by brennie** [comment]
I was using whatever the latest release on curseforge was at the time of posting. I have since removed JER, but I can try this and get back to you.

**Comment by way2muchnoise** [comment]
Closing due to no response
