### ISSUE TITLE
Profiling causes game to crash with Open Terrain Generator installed

### ISSUE THREAD

**Issue by UntouchedWagons** [way2muchnoise/JustEnoughResources#158]
Hi there. I'm using Open Terrain Generator with the Biome Bundle plugin (I guess that's what it would be called) and am using CoFH World to generate all the ores.

When I try to profile the modded ores the game crashes with this stack trace:

    java.lang.NullPointerException: Exception in server tick loop
        at com.pg85.otg.forge.events.ServerEventListener.tryTeleportPlayer(ServerEventListener.java:803)
        at com.pg85.otg.forge.events.ServerEventListener.TeleportPlayers(ServerEventListener.java:794)
        at com.pg85.otg.forge.events.ServerEventListener.onServerTick(ServerEventListener.java:606)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1286_ServerEventListener_onServerTick_ServerTickEvent.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:265)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
        at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)

Here's the full game log: https://paste.ee/p/eoQDb this stack trace appears on line 5162.

Let me know if there's any other info or testing you need done. I'd like to keep OTG and Biome Bundle, I like its terrain gen.

**Comment by UntouchedWagons** [comment]
Apparently the version of JER I downloaded from Curse is horribly out of date. I'll try updating it

**Comment by way2muchnoise** [comment]
This seems more like an issue for OTG
See PG85/OpenTerrainGenerator#185 and PG85/OpenTerrainGenerator#186
