### ISSUE TITLE
[1.12.2] JER runs out of memory at launch

### ISSUE THREAD

**Issue by HariboTer** [way2muchnoise/JustEnoughResources#237]
I know I'm running a lot of mods (to which I just added JER), but from previous startups I know that none of the other mods come even close to using the full 20 GB I'm giving Minecraft, so there is probably something wrong with the JER initialization process (maybe a cross mod conflict?). Here's the report:
[crash-2020-06-17_13.05.49-client.txt](https://github.com/way2muchnoise/JustEnoughResources/files/4792084/crash-2020-06-17_13.05.49-client.txt)

**Comment by way2muchnoise** [comment]
It seems like a mod conflict looking at
```
at org.cache2k.core.util.SimpleTimer.<init>(SimpleTimer.java:146)
    at org.cache2k.core.TimingHandler$Static.reset(TimingHandler.java:327)
    at org.cache2k.core.HeapCache.initializeHeapCache(HeapCache.java:379)
    at org.cache2k.core.HeapCache.initWithoutTimerHandler(HeapCache.java:342)
    at org.cache2k.core.HeapCache.init(HeapCache.java:334)
    at org.cache2k.core.InternalCache2kBuilder.buildAsIs(InternalCache2kBuilder.java:354)
    at org.cache2k.core.InternalCache2kBuilder.build(InternalCache2kBuilder.java:185)
    at org.cache2k.core.Cache2kCoreProviderImpl.createCache(Cache2kCoreProviderImpl.java:214)
    at org.cache2k.Cache2kBuilder.build(Cache2kBuilder.java:875)
    at net.minecraft.world.World.<init>(World.java:126)
    at jeresources.util.FakeClientWorld.<init>(FakeClientWorld.java:42)
```

To me this looks like a core mod changing how the worlds are stored and just doesn't allow me to create a second fake one on the side.

**Comment by way2muchnoise** [comment]
Not supporting 1.12 anymore, will have to rewrite profiling for newer versions.
