### ISSUE TITLE
Game crash rendering item

### ISSUE THREAD

**Issue by manuelcasper007** [way2muchnoise/JustEnoughResources#258]
Hello there, it's the first time I use this website so if I do something wrong let me know, the error is that im browsing for examples blocks and in the same page an icon of another mod, in this case Flans it crashes when it appears this is the whole error:

---- Minecraft Crash Report ----
// But it works on my machine.

Time: 28/09/20 22:45
Description: Rendering item

java.lang.NullPointerException: Rendering item
	at com.flansmod.common.driveables.ItemVehicle.func_77650_f(ItemVehicle.java:213)
	at net.minecraft.item.ItemStack.func_77954_c(ItemStack.java:117)
	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:403)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147051_a(GuiContainerCreative.java:929)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:760)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1455)
	at ctb.renders.CTBCameraRenderer.func_78480_b(CTBCameraRenderer.java:80)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.flansmod.common.driveables.ItemVehicle.func_77650_f(ItemVehicle.java:213)
	at net.minecraft.item.ItemStack.func_77954_c(ItemStack.java:117)
	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:403)

-- Item being rendered --
Details:
	Item Type: com.flansmod.common.driveables.ItemVehicle@29cebc53
	Item Aux: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147051_a(GuiContainerCreative.java:929)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:760)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (169, 84). Absolute: (339, 310)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1455)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityClientPlayerMP['MANUELCASPER1'/303, l='MpServer', x=725,59, y=76,77, z=739,88], MCH_ViewEntityDummy['McHeliDummyEntity'/597, l='MpServer', x=0,00, y=-4,00, z=0,00]]
	Chunk stats: MultiplayerChunkCache: 569, 578
	Level seed: 0
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (387,64,421), Chunk: (at 3,4,5 in 24,26; contains blocks 384,0,416 to 399,255,431), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 42142 game time, 131921 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 114 total; [EntityChicken['Pollo'/512, l='MpServer', x=696,34, y=68,00, z=728,34], EntityChicken['Pollo'/513, l='MpServer', x=688,44, y=70,00, z=719,56], EntityChicken['Pollo'/514, l='MpServer', x=710,38, y=67,00, z=735,44], EntityChicken['Pollo'/515, l='MpServer', x=689,25, y=69,00, z=736,13], EntityWitch['Bruja'/516, l='MpServer', x=681,75, y=25,00, z=753,69], EntityWitch['Bruja'/1540, l='MpServer', x=657,50, y=14,00, z=777,50], EntityItem['item.tile.torch'/518, l='MpServer', x=703,81, y=31,13, z=783,63], EntitySheep['Oveja'/519, l='MpServer', x=689,81, y=64,00, z=782,38], EntityWitch['Bruja'/1543, l='MpServer', x=647,50, y=44,00, z=660,50], EntitySheep['Oveja'/520, l='MpServer', x=691,50, y=64,00, z=782,50], EntitySheep['Oveja'/521, l='MpServer', x=691,50, y=65,00, z=779,50], EntitySheep['Oveja'/522, l='MpServer', x=688,63, y=64,00, z=783,25], EntityItem['item.tile.torch'/523, l='MpServer', x=702,66, y=31,13, z=785,88], EntityItem['item.tile.rail'/525, l='MpServer', x=703,13, y=32,13, z=803,09], EntityItem['item.tile.torch'/526, l='MpServer', x=703,81, y=32,13, z=802,34], EntityWitch['Bruja'/1552, l='MpServer', x=655,50, y=27,00, z=672,50], EntityWitch['Bruja'/529, l='MpServer', x=695,50, y=33,00, z=817,50], EntityWitch['Bruja'/1553, l='MpServer', x=658,50, y=27,00, z=672,50], EntityWitch['Bruja'/1554, l='MpServer', x=659,38, y=27,00, z=671,72], EntityWitch['Bruja'/532, l='MpServer', x=693,75, y=33,00, z=816,72], EntityItem['item.tile.cloth.white'/1309, l='MpServer', x=694,59, y=66,13, z=715,19], EntityItem['item.tile.cloth.white'/1577, l='MpServer', x=700,00, y=66,13, z=713,66], EntitySheep['Oveja'/555, l='MpServer', x=705,53, y=67,00, z=661,50], EntitySheep['Oveja'/557, l='MpServer', x=707,06, y=68,00, z=669,06], EntitySheep['Oveja'/558, l='MpServer', x=713,63, y=69,00, z=665,50], EntitySheep['Oveja'/559, l='MpServer', x=718,31, y=70,00, z=663,25], EntityItem['item.item.item_explorer'/304, l='MpServer', x=726,56, y=68,13, z=737,94], EntitySheep['Oveja'/560, l='MpServer', x=714,88, y=69,00, z=665,53], EntitySquid['Calamar'/563, l='MpServer', x=704,88, y=53,00, z=717,88], EntityItem['item.tile.rail'/564, l='MpServer', x=712,19, y=32,13, z=803,88], EntityItem['item.tile.rail'/565, l='MpServer', x=704,38, y=32,13, z=801,19], EntityClientPlayerMP['MANUELCASPER1'/303, l='MpServer', x=725,59, y=76,77, z=739,88], EntityWitch['Bruja'/583, l='MpServer', x=725,28, y=30,53, z=732,84], EntitySheep['Oveja'/584, l='MpServer', x=730,50, y=66,00, z=783,50], EntitySheep['Oveja'/585, l='MpServer', x=734,09, y=67,00, z=784,19], EntitySheep['Oveja'/586, l='MpServer', x=735,22, y=67,00, z=783,69], EntitySheep['Oveja'/587, l='MpServer', x=731,50, y=67,00, z=785,50], EntityItem['item.tile.groundcoverLeavesBRN'/588, l='MpServer', x=735,75, y=64,13, z=803,75], EntityItem['item.tile.groundcoverGrassGRNDK'/590, l='MpServer', x=733,75, y=64,13, z=800,03], EntityWitch['Bruja'/1618, l='MpServer', x=669,50, y=27,00, z=806,50], EntityWitch['Bruja'/1619, l='MpServer', x=654,50, y=44,00, z=672,50], MCH_ViewEntityDummy['McHeliDummyEntity'/597, l='MpServer', x=0,00, y=-4,00, z=0,00], EntityButterfly['Mariposa'/598, l='MpServer', x=708,79, y=67,12, z=755,75], EntityItem['item.tile.groundcoverGrassGRNDK'/599, l='MpServer', x=738,16, y=65,13, z=797,94], EntityItem['item.tile.groundcoverGrassGRNDK'/600, l='MpServer', x=736,94, y=65,13, z=798,59], EntityItem['item.tile.cloth.white'/1381, l='MpServer', x=693,22, y=67,13, z=717,00], EntityButterfly['Mariposa'/625, l='MpServer', x=760,97, y=73,00, z=701,53], EntitySheep['Oveja'/642, l='MpServer', x=777,63, y=67,00, z=753,81], EntitySheep['Oveja'/643, l='MpServer', x=781,50, y=67,00, z=748,50], EntitySheep['Oveja'/644, l='MpServer', x=776,63, y=65,00, z=760,47], EntitySheep['Oveja'/645, l='MpServer', x=775,34, y=66,00, z=761,28], EntitySheep['Oveja'/646, l='MpServer', x=776,91, y=65,00, z=763,31], EntitySheep['Oveja'/647, l='MpServer', x=781,50, y=65,00, z=767,72], EntitySheep['Oveja'/648, l='MpServer', x=783,50, y=66,00, z=753,50], EntitySheep['Oveja'/651, l='MpServer', x=785,47, y=67,00, z=749,25], EntitySheep['Oveja'/657, l='MpServer', x=803,50, y=67,00, z=762,50], EntitySheep['Oveja'/658, l='MpServer', x=803,50, y=67,00, z=762,50], EntitySheep['Oveja'/659, l='MpServer', x=801,50, y=66,00, z=762,50], EntitySheep['Oveja'/660, l='MpServer', x=803,50, y=66,00, z=760,50], EntityWitch['Bruja'/412, l='MpServer', x=654,53, y=44,00, z=670,88], EntityButterfly['Mariposa'/416, l='MpServer', x=654,75, y=64,00, z=671,56], EntityWitch['Bruja'/417, l='MpServer', x=653,31, y=44,00, z=674,75], EntityWitch['Bruja'/418, l='MpServer', x=652,44, y=44,00, z=676,56], EntityWitch['Bruja'/422, l='MpServer', x=654,31, y=44,00, z=679,34], EntityWitch['Bruja'/424, l='MpServer', x=651,50, y=50,00, z=691,50], EntityWitch['Bruja'/425, l='MpServer', x=652,50, y=50,00, z=690,50], EntityWitch['Bruja'/427, l='MpServer', x=651,50, y=50,00, z=693,50], EntitySheep['Oveja'/431, l='MpServer', x=650,56, y=74,00, z=702,66], EntityChicken['Pollo'/432, l='MpServer', x=653,56, y=73,00, z=711,56], EntitySheep['Oveja'/433, l='MpServer', x=655,38, y=74,00, z=720,47], EntityWitch['Bruja'/436, l='MpServer', x=654,50, y=36,00, z=787,50], EntityButterfly['Mariposa'/1721, l='MpServer', x=710,72, y=64,00, z=788,19], EntityButterfly['Mariposa'/1722, l='MpServer', x=767,50, y=65,00, z=796,97], EntityWitch['Bruja'/448, l='MpServer', x=660,28, y=27,00, z=670,84], EntityWitch['Bruja'/449, l='MpServer', x=663,50, y=23,00, z=673,50], EntityWitch['Bruja'/450, l='MpServer', x=660,50, y=26,00, z=673,50], EntitySheep['Oveja'/451, l='MpServer', x=659,75, y=72,00, z=707,41], EntityWitch['Bruja'/1475, l='MpServer', x=672,50, y=28,00, z=819,50], EntityChicken['Pollo'/452, l='MpServer', x=669,19, y=71,00, z=712,91], EntityChicken['Pollo'/453, l='MpServer', x=663,03, y=72,00, z=712,16], EntityChicken['Pollo'/454, l='MpServer', x=664,19, y=72,00, z=712,72], EntitySheep['Oveja'/455, l='MpServer', x=659,75, y=71,00, z=704,19], EntityWitch['Bruja'/457, l='MpServer', x=654,56, y=22,00, z=784,44], EntityMinecartChest['entity.MinecartChest.name'/459, l='MpServer', x=657,50, y=29,50, z=804,50], EntityWitch['Bruja'/462, l='MpServer', x=670,50, y=26,00, z=808,59], EntityBat['Murciélago'/1490, l='MpServer', x=650,59, y=50,00, z=691,94], EntityButterfly['Mariposa'/1491, l='MpServer', x=702,56, y=64,00, z=690,78], EntityButterfly['Mariposa'/1495, l='MpServer', x=794,53, y=73,00, z=682,41], EntityWMWolf['Lobo'/474, l='MpServer', x=686,50, y=67,00, z=688,50], EntityWMWolf['Lobo'/475, l='MpServer', x=685,53, y=66,00, z=690,94], EntitySheep['Oveja'/476, l='MpServer', x=681,50, y=69,00, z=714,47], EntitySheep['Oveja'/477, l='MpServer', x=681,50, y=69,00, z=715,53], EntitySheep['Oveja'/478, l='MpServer', x=681,50, y=70,00, z=719,50], EntitySheep['Oveja'/479, l='MpServer', x=680,50, y=70,00, z=723,50], EntityItem['item.tile.cloth.white'/1759, l='MpServer', x=692,19, y=67,13, z=718,56], EntityMinecartChest['entity.MinecartChest.name'/480, l='MpServer', x=687,50, y=25,50, z=755,50], EntityWitch['Bruja'/482, l='MpServer', x=679,13, y=25,00, z=755,44], EntityMinecartChest['entity.MinecartChest.name'/483, l='MpServer', x=679,50, y=23,50, z=779,50], EntityWitch['Bruja'/485, l='MpServer', x=676,50, y=23,00, z=779,50], EntityWitch['Bruja'/487, l='MpServer', x=672,50, y=26,00, z=815,50], EntityButterfly['Mariposa'/1769, l='MpServer', x=724,69, y=64,00, z=781,28], EntityWitch['Bruja'/1515, l='MpServer', x=649,50, y=16,00, z=784,50], EntityWitch['Bruja'/1516, l='MpServer', x=647,50, y=16,00, z=787,50], EntityWitch['Bruja'/1517, l='MpServer', x=648,50, y=16,00, z=788,50], EntityBat['Murciélago'/1773, l='MpServer', x=646,97, y=29,00, z=801,50], EntityWitch['Bruja'/1518, l='MpServer', x=648,50, y=16,00, z=790,50], EntityItem['item.item.item_explorer'/752, l='MpServer', x=725,81, y=66,13, z=738,13], EntitySheep['Oveja'/501, l='MpServer', x=700,88, y=66,00, z=668,81], EntitySheep['Oveja'/502, l='MpServer', x=702,34, y=66,00, z=661,75], EntityWMWolf['Lobo'/503, l='MpServer', x=701,50, y=65,00, z=681,91], EntityWMWolf['Lobo'/504, l='MpServer', x=693,53, y=67,00, z=720,00], EntitySquid['Calamar'/505, l='MpServer', x=703,22, y=53,00, z=719,81], EntityButterfly['Mariposa'/1787, l='MpServer', x=801,17, y=67,00, z=778,68], EntitySquid['Calamar'/511, l='MpServer', x=697,50, y=53,38, z=724,50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:425)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1613495704 bytes (1538 MB) / 9663676416 bytes (9216 MB) up to 9663676416 bytes (9216 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx9G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 103
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 77 mods loaded, 77 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	ivtoolkit{1.2.1} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal (1).jar) 
	UCHIJAAAA	voltzenginepreloader{0.0.1} [Voltz Engine Preloader] (minecraft.jar) 
	UCHIJAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHIJAAAA	AncientWarfare{2.4.114-beta-MC1.7.10} [Ancient Warfare Core] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	AncientWarfareAutomation{2.4.114-beta-MC1.7.10} [Ancient Warfare Automation] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	AncientWarfareNEIPlugin{2.4.114-beta-MC1.7.10} [Ancient Warfare NEI Plugin] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	AncientWarfareNpc{2.4.114-beta-MC1.7.10} [Ancient Warfare NPCs] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	AncientWarfareStructure{2.4.114-beta-MC1.7.10} [Ancient Warfare Structures] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	ArchitectureCraft{1.7.2} [ArchitectureCraft] (ArchitectureCraft-1.7.2-mc1.7.10.jar) 
	UCHIJAAAA	BetterFoliage{2.0.17} [Better Foliage] (BetterFoliage-MC1.7.10-2.0.17.jar) 
	UCHIJAAAA	betterloadingscreen{1.3.10} [Better Loading Screen] (BetterLoadingScreen-1.3.10.jar) 
	UCHIJAAAA	betterplacement{MC1.7.10-1.0.0-1} [Better Placement] (BetterPlacement-MC1.7.10-1.0.0-1.jar) 
	UCHIJAAAA	BiblioCraft{1.11.7} [BiblioCraft] (BiblioCraft[v1.11.7][MC1.7.10].jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar) 
	UCHIJAAAA	bff{1.0} [bff] (BlockFront.jar) 
	UCHIJAAAA	speedytoolsmod{2.1.0} [Build Faster Mod] (Build-Faster-Mod-1.7.10.zip) 
	UCHIJAAAA	ctbupdater{1.0} [Call to Battle Updater] (ctbupdater-1.7.10-1.0.0.jar) 
	UCHIJAAAA	ctb{5.0} [Call To Battle] (Call to Battle 2 (1).jar) 
	UCHIJAAAA	ctb-authsuccessor{1.0} [AuthSuccessor Authentication Engine] (Call to Battle 2 (1).jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.8.2} [Carpenter's Blocks] (Carpenter's+Blocks+v3.3.8.2+-+MC+1.7.10.jar) 
	UCHIJAAAA	one_point_twelve_concrete{v 1.0} [1.12 Concrete] (concreteMod-v1.0.jar) 
	UCHIJAAAA	creativecore{1.3.14} [CreativeCore] (CreativeCore-1.7.10.jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(29oct17).jar) 
	UCHIJAAAA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.4.2_1.7.10.jar) 
	UCHIJAAAA	props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.7.10.jar) 
	UCHIJAAAA	DynamicLights{1.3.9a} [Dynamic Lights] (Dynamic+Lights-1.3.9a-MC1.7.10.jar) 
	UCHIJAAAA	dsurround{1.0.6.4} [Dynamic Surroundings] (DynamicSurroundings-1.7.10-1.0.6.4.jar) 
	UCHIJAAAA	Eln{@VERSION@} [Electrical Age] (ElectricalAge-1.14.2 (2).jar) 
	UCHIJAAAA	flansmod{@VERSION@} [Flan's Mod Ultimate] (FlansModPlusUltimate1.1-1.7.10 (6).jar) 
	UCHIJAAAA	flenixroads{0.10.0} [FlenixRoads] (FlenixRoads_[1.7.10]-0.11.0-b43.jar) 
	UCHIJAAAA	hbm{1.0.27 BETA (3165)} [Hbm's Nuclear Tech] (hbm1.0.27_BETA3165.jar) 
	UCHIJAAAA	voltzengine{1.11.0.454} [Voltz Engine] (VoltzEngine-1.7.10-1.11.0b454.jar) 
	UCHIJAAAA	icbm{2.15.5.514} [ICBM] (ICBM-1.7.10-2.15.5b514.jar) 
	UCHIJAAAA	ImmersiveEngineering{0.7.7} [Immersive Engineering] (ImmersiveEngineering-0.7.7 (1).jar) 
	UCHIJAAAA	invention{1.0.0} [Invention] (Invention-1.0.0-Beta.jar) 
	UCHIJAAAA	ism{2.6.1 MC-1.7.10} [Instant Structures Mod (ISM)] (ism-2.6.1 MC-1.7.10.jar) 
	UCHIJAAAA	wolffsmod{1.0} [Wolff's NPCs] (l1.7.10l-Flan's-Mod-Vehicles-for-Custom-NPCs-1.0.jar) 
	UCHIJAAAA	littletiles{1.1.0} [LittleTiles] (LittleTiles+v1.2.0+mc1.7.10 (1).jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.13.0} [Malisis' Doors] (malisisdoors-1.7.10-1.13.0.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	RadixCore{2.1.3} [RadixCore] (RadixCore-1.7.10-2.1.3-universal.jar) 
	UCHIJAAAA	MCA{1.7.10-5.2.2} [Minecraft Comes Alive] (MCA-1.7.10-5.2.2-universal.jar) 
	UCHIJAAAA	mcheli{1.0.3} [MC Helicopter] (mcheli) 
	UCHIJAAAA	millenaire{6.0.1} [MillÃ©naire] (millenaire-6.0.2.jar) 
	UCHIJAAAA	NGTLib{1.7.10.27} [NGTLib] (NGTLib-1.7.10.zip) 
	UCHIJAAAA	parachutemod{1.7.10} [Parachute Mod] (parachutemod-1.7.10-2.5.6-01.jar) 
	UCHIJAAAA	plantmegapack{4.33} [Plant Mega Pack] (Plant-Mega-Pack-Mod-1.7.10.jar) 
	UCHIJAAAA	ProjectE{1.7.10-PE1.10.1} [ProjectE] (ProjectE-1.7.10-PE1.10.1.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.33-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-Base-1.7.10.jar) 
	UCHIJAAAA	ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] (ProjectRed-1.7.10-Lighting.jar) 
	UCHIJAAAA	DragonsRadioMod{1.7.0} [Dragon's Radio Mod] (Radio-Mod-1.7.10.jar) 
	UCHIJAAAA	row{1.7.10-5.8-RC7} [Rails of War] (RailsOfWar-1.7.10-5.8-RC7 (1).jar) 
	UCHIJAAAA	RTM{1.7.10.35} [RealTrainMod] (Real-Train-Mod-1.7.10.zip) 
	UCHIJAAAA	realisticpain{2.0} [Realistic Pain] (Realistic Pain-2.0-1.7.10.jar) 
	UCHIJAAAA	roadstuff{1.0.3-final} [Road Stuff] (RoadStuff-mc1.7.10-1.0.2-final.jar) 
	UCHIJAAAA	RTG{1.7.10-1.1.1.7} [Realistic Terrain Generation] (RTG-1.7.10-1.1.1.7(1).jar) 
	UCHIJAAAA	scm{1.7.10-0.2.02} [Saracalia's City Mod] (SCM-1.7.10-0.2.02.jar) 
	UCHIJAAAA	signpost{1.08.2} [Signpost] (signpost-1.7.10-1.08.2.jar) 
	UCHIJAAAA	sirenmod{2.1.1} [Mcrafter's Siren Mod (Pre-Release 2.1.01)] (Siren-Mod-1.7.10.jar) 
	UCHIJAAAA	SlimevoidLib{2.0.4.7} [Slimevoid Library] (SlimevoidLibrary-2.0.4.7.jar) 
	UCHIJAAAA	taleofkingdoms{1.0.12.4} [Tale of Kingdoms] (Tale+of+Kingdoms+1.7.10+-+B12.5.2.jar) 
	UCHIJAAAA	voltzenginemodcompat{1.11.0.454} [Voltz Engine Mod Compatibility Loader] (VoltzEngine-1.7.10-1.11.0b454.jar) 
	UCHIJAAAA	voltzenginemodflag{1.11.0.454} [VoltzEngine mod protection, flag, and region system] (VoltzEngine-1.7.10-1.11.0b454.jar) 
	UCHIJAAAA	wildmobsmod{1.5.3} [Wild Mobs] (WildMobs-1.7.10-1.5.3.jar) 
	UCHIJAAAA	yegamolchattels{1.1.2} [Ye Gamol Chattels] (YeGamolChattels-1.1.2.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: Español (España)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by manuelcasper007** [comment]
What Im saying is that I dont want to have mod icons change in mod sections, so like it only show a single item and doesnt change

**Comment by way2muchnoise** [comment]
Can you reproduce with just Flans and JER? (and of course any dependencies)

**Comment by manuelcasper007** [comment]
What you mean saying, reproduce, sorry im from Spain but I know quite good english XD

**Comment by way2muchnoise** [comment]
Can you make it crash in a mod pack that just has Flans, JER and only mods needed to run those 2

**Comment by manuelcasper007** [comment]
No, I think that the problem might be that that mod needs a diferrent version of flans, but the thing is, the actual one I have is the one that I need to play with all the flans items, but as I said, when I go to page 2, where flans vehicles I think it is, and shows a vehicle item it crashes. But ill try with...,what pack of mods? well ill search for one, thanks

**Comment by manuelcasper007** [comment]
But ill try it, thanks bro
