### ISSUE TITLE
[1.16.4] JER is not working

### ISSUE THREAD

**Issue by fFIRE332A** [way2muchnoise/JustEnoughResources#269]
JER is currently not working on a modpack I am creating. JEI itself is working (as well as its other addons I have added), but JER is not functioning at all and I am unsure why. I apologize if this is not the right place for the issue, I just did not know where else to post.

**Comment by way2muchnoise** [comment]
Version info?

**Comment by fFIRE332A** [comment]
0.12.0.103 on 1.16.4

**Comment by Nick-McKay** [comment]
I can confirm that villager trades work, but no other tabs work

**Comment by TwiiCe** [comment]
Can confirm the same issue. I do see dungeon chest loot and villager trading, but not oregen.
Added my config that is -as shipped-

#Range: 1 ~ 4
itemsPerColumn = 4
#Range: 1 ~ 4
itemsPerRow = 4
diyData = true
showDevData = false
enchantsBlacklist = ["flimflam", "soulBound"]
hiddenTabs = []
dimensionsBlacklist = [-11]

**Comment by fFIRE332A** [comment]
> Can confirm the same issue. I do see dungeon chest loot and villager trading, but not oregen.
> Added my config that is -as shipped-
> 
> #Range: 1 ~ 4
> itemsPerColumn = 4
> #Range: 1 ~ 4
> itemsPerRow = 4
> diyData = true
> showDevData = false
> enchantsBlacklist = ["flimflam", "soulBound"]
> hiddenTabs = []
> dimensionsBlacklist = [-11]

Yours is working perfectly fine, oregen is not in 1.16.4 yet because the profiling for the world is not in 1.16.4 to generate the oregen thing

**Comment by way2muchnoise** [comment]
![image](https://user-images.githubusercontent.com/5518998/104349605-6dc7b700-5503-11eb-91bd-c43671713741.png)

Everything seems to work fine when I did a fresh install from CurseForge:
- JEI version 7.6.1.65
- JER version 0.12.0.103
- Forge version 35.1.4

Do you have any other mods installed?

**Comment by Yourname942** [comment]
I have the same issue: 
Minecraft 1.16.4
Forge 35.1.29
Just Enough Resources: JustEnoughResources-1.16.4-0.12.0.104.jar
JEI jei-1.16.4-7.6.1.65.jar

Modlist: 
https://gist.github.com/Yourname942/fda49f3c33f625fb80eaf532c0195eff

**Comment by way2muchnoise** [comment]
Could anyone post a full client log of start up and world join? Jus to see if something is showing up there?

**Comment by Celivalg** [comment]
Pretty sure I'm having the same issue that is described above, 
Here is the log: https://pastebin.com/4r9zP2kW
Issue happens at [14:18:46] during world join.

Hope this helps track it down, I'm aware the pack I am building has other issues, but that's what I am trying to fix at the moment, hence why I am here, sorry for the dirty log (maybe some of the issues are related? at least if we can pin it down to something that would help)

**Comment by way2muchnoise** [comment]
Can't open your pastebin, says it has been removed. The jer_profile command not working is normal in the newer versions. It has not yet been reimplemented.

**Comment by GregoryDalessandro** [comment]
we also cannot see anything from JER:
Minecraft 1.16.5
Forge 36.0.39
JER 0.12.0.104
JEI 7.6.1.71

latest log: https://gist.github.com/GregoryDalessandro/b98f2430a9cb264b6616c3560986f643

**Comment by way2muchnoise** [comment]
That log clearly has a lot more mods that just JER (and deps). Also I don't see any loading from JEI or JER in the log, might need a different log (client?) to be of help.

**Comment by Celivalg** [comment]
Here is a log of an instance with only forge, jei and jer... here jer seems to be working but /jer_profile doesn't register as a command: https://paste.ee/p/6CNHe
By jer working I mean that I can see the resource distribution of coal for example, and that I don't get the error message... Still /jer_profile doesn't work (has the command been removed?)

Here is a log of an instance with many mods where jer doesn't work... I'm gonna try to update the mods and see if that fixes it but I'm not very hopeful... : https://paste.ee/p/iZMBM , issue happens at [10:04:11] (line 1947)

maybe the command /jer_profile is a different issue since it seems to not work in both cases.

I'm going to try to pin point which mod is conflicting if that is actually a conflict and not something else.

If the paste don't work anymore I'm gonna give up on those paste sites and just give the logs as files...

**Comment by way2muchnoise** [comment]
@Celivalg thanks for hunting that one down, should be able to fix that. As for the profile command, this has indeed not been reimplemented yet in 1.15+ (due to me not having a lot of time to mod anymore)

**Comment by TheDarkRisen** [comment]
Its not fixed yet?

**Comment by JackAlexRose** [comment]
This incompatibility with Ice and fire still appears to be an issue. 

- When I disable Citadel and Ice and Fire (and Alex's Mobs) JER works.
- When I have these mods enabled, I get the following error in the logs:
`[Render thread/WARN] [jeresources/]: Error during loading of default minecraft compat
java.lang.NullPointerException: null
	at jeresources.compatibility.minecraft.MobCompat.setExperience(MobCompat.java:53) ~[jeresources:0.12.0.100] {re:classloading}
	at jeresources.compatibility.minecraft.MinecraftCompat.registerMob(MinecraftCompat.java:45) ~[jeresources:0.12.0.100] {re:classloading}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_281] {}
	at java.util.stream.SortedOps$SizedRefSortingSink.end(Unknown Source) ~[?:1.8.0_281] {}
	at java.util.stream.Sink$ChainedReference.end(Unknown Source) ~[?:1.8.0_281] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_281] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_281] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_281] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_281] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_281] {}
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_281] {}
	at jeresources.compatibility.minecraft.MinecraftCompat.registerVanillaMobs(MinecraftCompat.java:55) ~[jeresources:0.12.0.100] {re:classloading}
	at jeresources.compatibility.minecraft.MinecraftCompat.init(MinecraftCompat.java:35) ~[jeresources:0.12.0.100] {re:classloading}
	at jeresources.compatibility.Compatibility.init(Compatibility.java:26) ~[jeresources:0.12.0.100] {re:classloading}
	at jeresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:14) ~[jeresources:0.12.0.100] {re:classloading}
	at jeresources.jei.JEIConfig.registerCategories(JEIConfig.java:71) ~[jeresources:0.12.0.100] {re:classloading}
	at mezz.jei.load.PluginLoader.lambda$new$3(PluginLoader.java:108) ~[jei:7.7.1.126] {re:classloading}
	at mezz.jei.load.PluginCaller.callOnPlugins(PluginCaller.java:26) ~[jei:7.7.1.126] {re:classloading}
	at mezz.jei.load.PluginLoader.<init>(PluginLoader.java:108) ~[jei:7.7.1.126] {re:classloading}
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:69) ~[jei:7.7.1.126] {re:classloading}
	at mezz.jei.startup.ClientLifecycleHandler.startJEI(ClientLifecycleHandler.java:147) ~[jei:7.7.1.126] {re:classloading}
	at mezz.jei.startup.ClientLifecycleHandler.setupJEI(ClientLifecycleHandler.java:140) ~[jei:7.7.1.126] {re:classloading}
	at mezz.jei.startup.ClientLifecycleHandler.lambda$new$3(ClientLifecycleHandler.java:106) ~[jei:7.7.1.126] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onRecipesUpdated(ForgeHooksClient.java:711) ~[forge:?] {re:classloading}
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_199525_a(ClientPlayNetHandler.java:1314) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:27) ~[?:?] {re:classloading}
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:15) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:36) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:189) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:151) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:128) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:outer_end.mixins.json:BackgroundMusicMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:outer_end.mixins.json:BackgroundMusicMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.8-launcher.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:52) [ForgeWrapper-1.5.1.jar:1.5.1] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}`

**Comment by 4AC11** [comment]
This is still not fixed :c 
Anyone know of any workarounds?
