### ISSUE TITLE
Mob drops is empty in 1.18.X while play on servers

### ISSUE THREAD

**Issue by GordonHollow** [way2muchnoise/JustEnoughResources#338]
When play on server, local or not - mob drop tab don't work, it just empty even with vanilla mobs.

In singlplayer - all work fine

Try diff version from 1.18.1 alpha release to current latest 1.18.2 release

**Comment by way2muchnoise** [comment]
What is the exact version of JER/JEI you are running? Any other mods involved?  
Can you share a client log from when you join a server?

**Comment by GordonHollow** [comment]
jei-1.18.2-9.7.0.193
JustEnoughResources-1.18.2-0.14.1.167

That's now, but this issue was here in every 1.18 versions i play, start from 1.18.1

many other mods involved, ATM7 modpack

`[11:00:38] [Thread-60/ERROR]: An error occurred building event handler
java.lang.NullPointerException: Cannot invoke "java.lang.ClassLoader.loadClass(String)" because the return value of "java.lang.Thread.getContextClassLoader()" is null
	at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:62) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:21) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:20) ~[eventbus-5.0.3.jar:5.0.3+70+master.d7d405b]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.optifine.GlErrors.getGlError(GlErrors.java:67) ~[?:?]
	at net.optifine.GlErrors.isEnabled(GlErrors.java:56) ~[?:?]
	at com.mojang.blaze3d.platform.GlDebug.m_84038_(GlDebug.java:169) ~[?:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) [lwjgl-opengl-3.2.2.jar%2346!/:build 10]
[11:00:38] [Thread-60/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. No active program.)
java.lang.Exception: Stack trace
	at com.mojang.blaze3d.platform.GlDebug.m_84038_(GlDebug.java:180) ~[?:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) [lwjgl-opengl-3.2.2.jar%2346!/:build 10]
[11:00:38] [Thread-60/ERROR]: An error occurred building event handler
java.lang.NullPointerException: Cannot invoke "java.lang.ClassLoader.loadClass(String)" because the return value of "java.lang.Thread.getContextClassLoader()" is null
	at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:62) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:21) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:20) ~[eventbus-5.0.3.jar:5.0.3+70+master.d7d405b]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at com.mojang.blaze3d.platform.GlDebug.m_84038_(GlDebug.java:190) ~[?:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) [lwjgl-opengl-3.2.2.jar%2346!/:build 10]
[11:00:38] [Thread-60/ERROR]: An error occurred building event handler
java.lang.NullPointerException: Cannot invoke "java.lang.ClassLoader.loadClass(String)" because the return value of "java.lang.Thread.getContextClassLoader()" is null
	at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:62) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:21) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:20) ~[eventbus-5.0.3.jar:5.0.3+70+master.d7d405b]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at com.mojang.blaze3d.platform.GlDebug.m_84038_(GlDebug.java:214) ~[?:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) [lwjgl-opengl-3.2.2.jar%2346!/:build 10]
[11:00:38] [Render thread/ERROR]: [Shaders] OpenGL error: 1282 (Invalid operation), program: gbuffers_textured, at: alphaTestRef
[11:00:38] [Thread-60/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. No active program.)
java.lang.Exception: Stack trace
	at com.mojang.blaze3d.platform.GlDebug.m_84038_(GlDebug.java:180) ~[?:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) [lwjgl-opengl-3.2.2.jar%2346!/:build 10]
[11:00:38] [Render thread/ERROR]: [Shaders] OpenGL error: 1282 (Invalid operation), program: gbuffers_textured_lit (gbuffers_textured), at: gbufferModelView
[11:00:38] [Thread-60/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. No active program.)
java.lang.Exception: Stack trace
	at com.mojang.blaze3d.platform.GlDebug.m_84038_(GlDebug.java:180) ~[?:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) [lwjgl-opengl-3.2.2.jar%2346!/:build 10]
[11:00:38] [Render thread/ERROR]: [Shaders] OpenGL error: 1282 (Invalid operation), program: gbuffers_textured_lit (gbuffers_textured), at: gbufferModelViewInverse
[11:00:38] [Thread-60/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. No active program.)
java.lang.Exception: Stack trace
	at com.mojang.blaze3d.platform.GlDebug.m_84038_(GlDebug.java:180) ~[?:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) [lwjgl-opengl-3.2.2.jar%2346!/:build 10]
[11:00:38] [Render thread/ERROR]: [Shaders] OpenGL error: 1282 (Invalid operation), program: gbuffers_textured_lit (gbuffers_textured), at: gbufferProjectionInverse
[11:00:38] [Thread-60/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. No active program.)
java.lang.Exception: Stack trace
	at com.mojang.blaze3d.platform.GlDebug.m_84038_(GlDebug.java:180) ~[?:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) [lwjgl-opengl-3.2.2.jar%2346!/:build 10]
[11:00:38] [Render thread/ERROR]: [Shaders] OpenGL error: 1282 (Invalid operation), program: gbuffers_textured_lit (gbuffers_textured), at: shadowProjection
[11:00:38] [Thread-60/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. No active program.)
java.lang.Exception: Stack trace
	at com.mojang.blaze3d.platform.GlDebug.m_84038_(GlDebug.java:180) ~[?:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) [lwjgl-opengl-3.2.2.jar%2346!/:build 10]
[11:00:38] [Render thread/ERROR]: [Shaders] OpenGL error: 1282 (Invalid operation), program: gbuffers_textured_lit (gbuffers_textured), at: shadowModelView
[11:00:38] [Thread-60/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. No active program.)
java.lang.Exception: Stack trace
	at com.mojang.blaze3d.platform.GlDebug.m_84038_(GlDebug.java:180) ~[?:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) [lwjgl-opengl-3.2.2.jar%2346!/:build 10]
[11:00:38] [Render thread/ERROR]: [Shaders] OpenGL error: 1282 (Invalid operation), program: gbuffers_textured_lit (gbuffers_textured), at: isEyeInCave
[11:00:40] [Render thread/INFO]: Loaded 1 waypoints from C:\Users\Mikhail\Documents\curseforge\minecraft\Instances\All the Mods 7 - ATM7 - 1.18.2\journeymap\data\mp\~Minecraft_57af5298~ab76~4f29~ac90~864b8cebb715\waypoints
[11:00:40] [Render thread/INFO]: Mapping started in C:\Users\Mikhail\Documents\curseforge\minecraft\Instances\All the Mods 7 - ATM7 - 1.18.2\journeymap\data\mp\~Minecraft_57af5298~ab76~4f29~ac90~864b8cebb715\overworld. Memory: 8000MB total, 4866MB free 
[11:00:42] [Render thread/WARN]: attempting to load item into food list that is no longer edible: minecraft:air (ignoring in case it becomes edible again later)
[11:00:44] [Render thread/INFO]: [Shaders] Framebuffer created: dfb
[11:00:44] [Render thread/WARN]: Image not found: alexsmobs:textures/entity_icon/mimic_octopus.png
[11:00:44] [Render thread/WARN]: Image not found: occultism:textures/entity_icon/marid.png
[11:00:44] [Render thread/WARN]: Image not found: minecraft:textures/entity_icon/villager/immersiveengineering:anvil.png
[11:00:44] [Render thread/WARN]: Image not found: alexsmobs:textures/entity_icon/crocodile_0.png
[11:00:44] [JM-texture-3/WARN]: Can't bind texture: 
java.lang.IllegalStateException: Rendersystem called from wrong thread
	at com.mojang.blaze3d.systems.RenderSystem.m_187556_(RenderSystem.java:183) ~[client-1.18.2-20220404.173914-srg.jar%23319!/:?]
	at com.mojang.blaze3d.systems.RenderSystem.m_187555_(RenderSystem.java:161) ~[client-1.18.2-20220404.173914-srg.jar%23319!/:?]
	at net.minecraft.client.renderer.texture.AbstractTexture.m_117963_(AbstractTexture.java:66) ~[client-1.18.2-20220404.173914-srg.jar%23319!/:?]
	at journeymap.client.render.texture.TextureImpl.m_117966_(TextureImpl.java:209) [journeymap-1.18.2-5.8.2-forge.jar%23198!/:1.18.2-5.8.2]
	at journeymap.client.render.texture.TextureImpl.m_117963_(TextureImpl.java:310) [journeymap-1.18.2-5.8.2-forge.jar%23198!/:1.18.2-5.8.2]
	at net.minecraft.client.renderer.texture.TextureManager.m_118495_(TextureManager.java:106) [client-1.18.2-20220404.173914-srg.jar%23319!/:?]
	at journeymap.client.render.texture.TextureCache.getTexture(TextureCache.java:211) [journeymap-1.18.2-5.8.2-forge.jar%23198!/:1.18.2-5.8.2]
	at journeymap.client.render.draw.DrawMarkerStep$1.call(DrawMarkerStep.java:103) [journeymap-1.18.2-5.8.2-forge.jar%23198!/:1.18.2-5.8.2]
	at journeymap.client.render.draw.DrawMarkerStep$1.call(DrawMarkerStep.java:96) [journeymap-1.18.2-5.8.2-forge.jar%23198!/:1.18.2-5.8.2]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[11:00:44] [Render thread/INFO]: [CHAT] §eJourneyMap:§f Нажмите [§bX§f].`

client log on join mostly spam Optifine GL errors, nothing about JER

**Comment by way2muchnoise** [comment]
Is this still an issue?

**Comment by GordonHollow** [comment]
> Is this still an issue?

on latest ATM7 - yes, 1.18

don't check 1.19 yet, idk about this version

**Comment by way2muchnoise** [comment]
Could you please post a full client log from launch until after joining a server (gist or pastebin).

**Comment by GordonHollow** [comment]
[latest.log](https://github.com/way2muchnoise/JustEnoughResources/files/9573828/latest.log)
Here it is, there is bunch of render errors spam, but nothing about JER

**Comment by falxie** [comment]
I'm also experiencing this in my modpack, any way I can help?

**Comment by Saereth** [comment]
We are having this issue in FTB Inferno as well, 
JEI version: jei-1.18.2-9.7.1.255
JER Version: JustEnoughResources-1.18.2-0.14.1.171

**Comment by RickieGamer** [comment]
Still an issue in 1.19.2
Tested with all the mods listed below, none showed mob drops while connected to a server
Server had all the same mods installed, only vanilla mob drops were shown
Forge 43.1.43
jei-1.19.2-forge-11.3.0.271
JustEnoughResources-1.19.2-1.1.0.179
blue_skies-1.19.2-1.3.20
DivineRPG-1.9.5
The_Undergarden-1.19.2-0.8.2
twilightforest-1.19-4.2.1421

**Comment by in-op** [comment]
_Still_ an issue. I'm using Fabric 1.19.2

**Comment by GordonHollow** [comment]
I figured out what's causing this!
I have datapack for all mob heads drop - and this break JER on server
Probably any mod that add mob drops via vanilla datapack methods can cause this, so maybe JER need some rewriting

**Comment by RickieGamer** [comment]
Updated server and client to JustEnoughResources-1.19.2-1.2.2.200.jar, and now on top of modded mobs not showing vanilla mobs no longer show on server

**Comment by Epicbaconflips** [comment]
> I figured out what's causing this! I have datapack for all mob heads drop - and this break JER on server Probably any mod that add mob drops via vanilla datapack methods can cause this, so maybe JER need some rewriting

What mod is it that's causing this problem?

**Comment by GordonHollow** [comment]
> > I figured out what's causing this! I have datapack for all mob heads drop - and this break JER on server Probably any mod that add mob drops via vanilla datapack methods can cause this, so maybe JER need some rewriting
> 
> What mod is it that's causing this problem?

Exactly as i say - datapack moremobheads, not the mod
It's from vanillatweaks

I suppose that some other mods can cause this issue - if they use vanilla datapack methods for modification loot tables from mobs

**Comment by OpticFusion1** [comment]
Still an issue for All The Mods 7 (1.18.1) as well.
JER 0.14.1.171
JEI 10.2.1.1004

**Comment by OpticFusion1** [comment]
Still has the same issue on the All The Mods 7 modpack (1.18.2).
JEI: 10.2.1.1004
JER: 0.14.1.171

The Dungeons Chest menu is empty as well, and the rest of the menus don't take into account modded items

**Comment by MacChuck** [comment]
Seeing this issue as well (and ore gen graphs) on a custom pack for 1.18.2.
JEI: 10.2.1.1005
JER: 0.14.1.171
Forge: 40.2.10

If I launch MC, load a single player save, go back to the main menu, and THEN connect to the server, JER will work. (for a while, at least)
