### ISSUE TITLE
1.16.5 incompatibility with JER and Feywild

### ISSUE THREAD

**Issue by SaphieNyako** [way2muchnoise/JustEnoughResources#340]
When Feywild is installed with JER loot table recipes tabs of JER aren't shown anymore.

1.16.5
Feywild - 1.16.5 - 2.1.2
Forge 36.2.31

**Comment by SaphieNyako** [comment]
It's not our JEI plugin, I disabled that completely and it still happens.
Its not our way of adding to loot tables, disabled that too and it still happens.
I can't find any events that could disturb theirs.
I tried compair with other mods but we arent doing anything different.

**Comment by way2muchnoise** [comment]
Could you post a full (client) log? Something must be going wrong and should be spit out there :)

**Comment by SaphieNyako** [comment]
Anything we can work with?

**Comment by way2muchnoise** [comment]
issue seems be in JEI loading, can you make sure no JEI interaction is present in Feywild when testing?

```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at mezz.jei.load.PluginCaller.callOnPlugins(PluginCaller.java:21)
	at mezz.jei.load.PluginLoader.<init>(PluginLoader.java:109)
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:69)
	at mezz.jei.startup.ClientLifecycleHandler.startJEI(ClientLifecycleHandler.java:147)
	at mezz.jei.startup.ClientLifecycleHandler.setupJEI(ClientLifecycleHandler.java:140)
	at mezz.jei.startup.ClientLifecycleHandler.lambda$new$3(ClientLifecycleHandler.java:106)
	at mezz.jei.startup.ClientLifecycleHandler$$Lambda$4380/1974708900.accept(Unknown Source)
```

**Comment by SaphieNyako** [comment]
I found the cause of the problem: 
https://github.com/SaphieNyako/Feywild/blob/80ba1c3bf1cd4adf2db4b994fafe184d048d08d7/src/main/java/com/feywild/feywild/network/TradesHandler.java#L15

If I remove the reload everything seems to work fine...
Though if changes are made to a datapack it might cause problems. 

I'll make a update for feywild 1.16, also will change it in the 1.18 version.

**Comment by SaphieNyako** [comment]
https://www.curseforge.com/minecraft/mc-mods/feywild/files/3843666

version 2.1.3 should fix the issue!
