### ISSUE TITLE
JER and Villagers and Monsters Mod Mob Drops Not Working

### ISSUE THREAD

**Issue by btwhitebear** [way2muchnoise/JustEnoughResources#354]
java.lang.StringIndexOutOfBoundsException: String index out of range: 1
	at java.lang.String.substring(String.java:1951) ~[?:1.8.0_51]
	at jeresources.util.MobHelper.getExpandedName(MobHelper.java:20) ~[?:0.12.1.128]
	at jeresources.entry.MobEntry.getMobName(MobEntry.java:80) ~[?:0.12.1.128]
	at jeresources.compatibility.minecraft.MinecraftCompat$$Lambda$8380/705030460.apply(Unknown Source) ~[?:?]
	at java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:469) ~[?:1.8.0_51]
	at java.util.Comparator$$Lambda$245/136157810.compare(Unknown Source) ~[?:?]
	at java.util.TimSort.binarySort(TimSort.java:292) ~[?:1.8.0_51]
	at java.util.TimSort.sort(TimSort.java:235) ~[?:1.8.0_51]
	at java.util.Arrays.sort(Arrays.java:1512) ~[?:1.8.0_51]
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:348) ~[?:1.8.0_51]
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51]
	at jeresources.compatibility.minecraft.MinecraftCompat.registerVanillaMobs(MinecraftCompat.java:56) ~[?:0.12.1.128]
	at jeresources.compatibility.minecraft.MinecraftCompat.init(MinecraftCompat.java:36) ~[?:0.12.1.128]
	at jeresources.compatibility.Compatibility.init(Compatibility.java:26) [?:0.12.1.128]
	at jeresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:14) [?:0.12.1.128]
	at jeresources.jei.JEIConfig.registerCategories(JEIConfig.java:71) [?:0.12.1.128]
	at mezz.jei.load.PluginLoader.lambda$new$3(PluginLoader.java:109) [?:7.7.1.152]
	at mezz.jei.load.PluginLoader$$Lambda$8266/877323851.accept(Unknown Source) [?:7.7.1.152]
	at mezz.jei.load.PluginCaller.callOnPlugins(PluginCaller.java:26) [?:7.7.1.152]
	at mezz.jei.load.PluginLoader.<init>(PluginLoader.java:109) [?:7.7.1.152]
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:69) [?:7.7.1.152]
	at mezz.jei.startup.ClientLifecycleHandler.startJEI(ClientLifecycleHandler.java:147) [?:7.7.1.152]
	at mezz.jei.startup.ClientLifecycleHandler.setupJEI(ClientLifecycleHandler.java:140) [?:7.7.1.152]
	at mezz.jei.startup.ClientLifecycleHandler.lambda$new$3(ClientLifecycleHandler.java:106) [?:7.7.1.152]
	at mezz.jei.startup.ClientLifecycleHandler$$Lambda$6044/1698200103.accept(Unknown Source) [?:7.7.1.152]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2939/378006273.invoke(Unknown Source) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$3160/1603181740.invoke(Unknown Source) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.client.ForgeHooksClient.onRecipesUpdated(ForgeHooksClient.java:786) [?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_199525_a(ClientPlayNetHandler.java:1314) [?:?]
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:27) [?:?]
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:15) [?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) [?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$8193/1822303698.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:948) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.34.jar:36.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$450/1530870688.call(Unknown Source) [forge-1.16.5-36.2.34.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]

**Comment by way2muchnoise** [comment]
JER 0.12 is for MC 1.16.5 which I'm no longer supporting
