### ISSUE TITLE
Not working on 1.19

### ISSUE THREAD

**Issue by reckonedstormlight** [way2muchnoise/JustEnoughResources#362]
I've built a pack for myself and my friends and I have found that JER isn't working in it. I figured it had to be a mod interaction so I made a test profile with just JEI and JER and it still shows nothing when I click on ores/ingots/anything in JEI to show the recipe. How can I get it to work?

MC: 1.19
Forge: 41.1.0
JER: 1.19-1.0.0.176

**Comment by JuggerReviry** [comment]
Same Problem here.

MC: 1.19.2
Forge: 43.1.32
JER: 1.19.2-forge-11.3.0.262

**Comment by T1MOXA** [comment]
MC: 1.19.2
Fabric Loader: 0.14.10
JER: Fabric-1.19.2-1.1.0.179

```
[14:39:21] [Render thread/INFO]: Registering categories: minecraft:jeresources ...
[14:39:21] [Render thread/ERROR]: Caught an error from mod plugin: class jeresources.jei.JEIConfig minecraft:jeresources
java.lang.UnsupportedOperationException: null
	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.28) ~[?:?]
	at jdk.nio.zipfs.ZipPath.toFile(Unknown Source) ~[jdk.zipfs:?]
	at jeresources.fabric.ModInfo.getPackResources(ModInfo.java:23) ~[JustEnoughResources-Fabric-1.19.2-1.1.0.179.jar:?]
	at jeresources.util.LootTableHelper.lambda$getLootTables$11(LootTableHelper.java:179) ~[JustEnoughResources-Fabric-1.19.2-1.1.0.179.jar:?]
	at java.lang.Iterable.forEach(Unknown Source) ~[?:?]
	at jeresources.util.LootTableHelper.getLootTables(LootTableHelper.java:179) ~[JustEnoughResources-Fabric-1.19.2-1.1.0.179.jar:?]
	at jeresources.util.LootTableHelper.toDrops(LootTableHelper.java:96) ~[JustEnoughResources-Fabric-1.19.2-1.1.0.179.jar:?]
	at jeresources.util.PlantHelper.getSeeds(PlantHelper.java:14) ~[JustEnoughResources-Fabric-1.19.2-1.1.0.179.jar:?]
	at jeresources.entry.PlantEntry.registerGrass(PlantEntry.java:28) ~[JustEnoughResources-Fabric-1.19.2-1.1.0.179.jar:?]
	at jeresources.registry.PlantRegistry.<init>(PlantRegistry.java:25) ~[JustEnoughResources-Fabric-1.19.2-1.1.0.179.jar:?]
	at jeresources.registry.PlantRegistry.getInstance(PlantRegistry.java:19) ~[JustEnoughResources-Fabric-1.19.2-1.1.0.179.jar:?]
	at jeresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:11) ~[JustEnoughResources-Fabric-1.19.2-1.1.0.179.jar:?]
	at jeresources.jei.JEIConfig.registerCategories(JEIConfig.java:98) ~[JustEnoughResources-Fabric-1.19.2-1.1.0.179.jar:?]
	at mezz.jei.common.load.PluginLoader.lambda$createRecipeCategories$3(PluginLoader.java:137) ~[jei-1.19.2-fabric-11.3.0.271.jar:?]
	at mezz.jei.common.load.PluginCaller.callOnPlugins(PluginCaller.java:25) ~[jei-1.19.2-fabric-11.3.0.271.jar:?]
	at mezz.jei.common.load.PluginLoader.createRecipeCategories(PluginLoader.java:137) ~[jei-1.19.2-fabric-11.3.0.271.jar:?]
	at mezz.jei.common.load.PluginLoader.createRecipeManager(PluginLoader.java:164) ~[jei-1.19.2-fabric-11.3.0.271.jar:?]
	at mezz.jei.common.startup.JeiStarter.start(JeiStarter.java:87) ~[jei-1.19.2-fabric-11.3.0.271.jar:?]
	at mezz.jei.fabric.startup.ClientLifecycleHandler.startJei(ClientLifecycleHandler.java:96) ~[jei-1.19.2-fabric-11.3.0.271.jar:?]
	at mezz.jei.fabric.startup.ClientLifecycleHandler.lambda$registerEvents$1(ClientLifecycleHandler.java:70) ~[jei-1.19.2-fabric-11.3.0.271.jar:?]
	at mezz.jei.fabric.events.JeiLifecycleEvents.lambda$static$4(JeiLifecycleEvents.java:28) ~[jei-1.19.2-fabric-11.3.0.271.jar:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.handler$dci002$handleUpdateRecipes(ClientPlayNetworkHandler:9972) ~[?:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onSynchronizeRecipes(ClientPlayNetworkHandler:1310) ~[?:?]
	at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.apply(SynchronizeRecipesS2CPacket:32) ~[?:?]
	at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.apply(SynchronizeRecipesS2CPacket:14) ~[?:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:22) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.redirect$zld000$redirectExecuteTask(ThreadExecutor:1021) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:116) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1129) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:768) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.10.jar:?]
```

**Comment by reckonedstormlight** [comment]
> MC: 1.19.2 Fabric Loader: 0.14.10 JER: Fabric-1.19.2-1.1.0.179
> 
> ```
> [14:39:21] [Render thread/INFO]: Registering categories: minecraft:jeresources ...
> [14:39:21] [Render thread/ERROR]: Caught an error from mod plugin: class jeresources.jei.JEIConfig minecraft:jeresources
> java.lang.UnsupportedOperationException: null
> 	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.28) ~[?:?]
> 	at jdk.nio.zipfs.ZipPath.toFile(Unknown Source) ~[jdk.zipfs:?]
> 	at jeresources.fabric.ModInfo.getPackResources(ModInfo.java:23) ~[JustEnoughResources-Fabric-1.19.2-1.1.0.179.jar:?]
> 	at jeresources.util.LootTableHelper.lambda$getLootTables$11(LootTableHelper.java:179) ~[JustEnoughResources-Fabric-1.19.2-1.1.0.179.jar:?]
> 	at java.lang.Iterable.forEach(Unknown Source) ~[?:?]
> 	at jeresources.util.LootTableHelper.getLootTables(LootTableHelper.java:179) ~[JustEnoughResources-Fabric-1.19.2-1.1.0.179.jar:?]
> 	at jeresources.util.LootTableHelper.toDrops(LootTableHelper.java:96) ~[JustEnoughResources-Fabric-1.19.2-1.1.0.179.jar:?]
> 	at jeresources.util.PlantHelper.getSeeds(PlantHelper.java:14) ~[JustEnoughResources-Fabric-1.19.2-1.1.0.179.jar:?]
> 	at jeresources.entry.PlantEntry.registerGrass(PlantEntry.java:28) ~[JustEnoughResources-Fabric-1.19.2-1.1.0.179.jar:?]
> 	at jeresources.registry.PlantRegistry.<init>(PlantRegistry.java:25) ~[JustEnoughResources-Fabric-1.19.2-1.1.0.179.jar:?]
> 	at jeresources.registry.PlantRegistry.getInstance(PlantRegistry.java:19) ~[JustEnoughResources-Fabric-1.19.2-1.1.0.179.jar:?]
> 	at jeresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:11) ~[JustEnoughResources-Fabric-1.19.2-1.1.0.179.jar:?]
> 	at jeresources.jei.JEIConfig.registerCategories(JEIConfig.java:98) ~[JustEnoughResources-Fabric-1.19.2-1.1.0.179.jar:?]
> 	at mezz.jei.common.load.PluginLoader.lambda$createRecipeCategories$3(PluginLoader.java:137) ~[jei-1.19.2-fabric-11.3.0.271.jar:?]
> 	at mezz.jei.common.load.PluginCaller.callOnPlugins(PluginCaller.java:25) ~[jei-1.19.2-fabric-11.3.0.271.jar:?]
> 	at mezz.jei.common.load.PluginLoader.createRecipeCategories(PluginLoader.java:137) ~[jei-1.19.2-fabric-11.3.0.271.jar:?]
> 	at mezz.jei.common.load.PluginLoader.createRecipeManager(PluginLoader.java:164) ~[jei-1.19.2-fabric-11.3.0.271.jar:?]
> 	at mezz.jei.common.startup.JeiStarter.start(JeiStarter.java:87) ~[jei-1.19.2-fabric-11.3.0.271.jar:?]
> 	at mezz.jei.fabric.startup.ClientLifecycleHandler.startJei(ClientLifecycleHandler.java:96) ~[jei-1.19.2-fabric-11.3.0.271.jar:?]
> 	at mezz.jei.fabric.startup.ClientLifecycleHandler.lambda$registerEvents$1(ClientLifecycleHandler.java:70) ~[jei-1.19.2-fabric-11.3.0.271.jar:?]
> 	at mezz.jei.fabric.events.JeiLifecycleEvents.lambda$static$4(JeiLifecycleEvents.java:28) ~[jei-1.19.2-fabric-11.3.0.271.jar:?]
> 	at net.minecraft.client.network.ClientPlayNetworkHandler.handler$dci002$handleUpdateRecipes(ClientPlayNetworkHandler:9972) ~[?:?]
> 	at net.minecraft.client.network.ClientPlayNetworkHandler.onSynchronizeRecipes(ClientPlayNetworkHandler:1310) ~[?:?]
> 	at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.apply(SynchronizeRecipesS2CPacket:32) ~[?:?]
> 	at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.apply(SynchronizeRecipesS2CPacket:14) ~[?:?]
> 	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:22) ~[?:?]
> 	at net.minecraft.util.thread.ThreadExecutor.redirect$zld000$redirectExecuteTask(ThreadExecutor:1021) ~[?:?]
> 	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
> 	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:116) ~[?:?]
> 	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1129) ~[?:?]
> 	at net.minecraft.client.MinecraftClient.run(MinecraftClient:768) ~[?:?]
> 	at net.minecraft.client.main.Main.main(Main:244) [client-intermediary.jar:?]
> 	at net.minecraft.client.main.Main.main(Main:51) [client-intermediary.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.10.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.10.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.10.jar:?]
> ```

what does this mean and why did you post it? Genuinely confused

**Comment by Anoyomouse** [comment]
I dug through the code, if you go into your `jeresources.toml` and `jeresources-common.toml` and set `disableLootManagerReloading = true` the mod should now at least load up.

I've found a couple more issues when rendering entities, but at least you'll get some of the functionality of JER

**Comment by way2muchnoise** [comment]
Are these issues with just JER and JEI installed? Or any other mods involved?

**Comment by reckonedstormlight** [comment]
> Are these issues with just JER and JEI installed? Or any other mods involved?

This issue persists even when it's just JER and JEI installed

**Comment by therealfakegamerboy** [comment]
> I dug through the code, if you go into your `jeresources.toml` and `jeresources-common.toml` and set `disableLootManagerReloading = true` the mod should now at least load up.
> 
> I've found a couple more issues when rendering entities, but at least you'll get some of the functionality of JER

I'm running All the Mods 8 (Minecraft 1.19.2) on my dedicated server and this fix didn't work. Anyone else still having this problem?
