### ISSUE TITLE
Integration issue with StellarSky mod

### ISSUE THREAD

**Issue by Markus-SJ** [way2muchnoise/JustEnoughResources#404]
Steps to reproduce:

1. MC 1.12.2 with Forge 14.23.5.2859
2. Add JEI, JER (and API), StellarSky and (Stellar API dependency) mods
3. Run and check logs

I tested running JER only with the Stellar API and no errors are thrown.

[JER, and Stellar API - All Fine.log](https://github.com/way2muchnoise/JustEnoughResources/files/11987213/JER.and.Stellar.API.-.All.Fine.log)
[JER, StellarSky, and Stellar API - sad face.log](https://github.com/way2muchnoise/JustEnoughResources/files/11987214/JER.StellarSky.and.Stellar.API.-.sad.face.log)

**Comment by way2muchnoise** [comment]
Seems like StellarSky doesn't like me creating a fake world
```
java.lang.NullPointerException: null
	at stellarium.stellars.StellarManager.loadOrCreateManager(StellarManager.java:26) ~[StellarManager.class:?]
	at stellarium.StellarForgeEventHook.preAttachCapabilities(StellarForgeEventHook.java:20) ~[StellarForgeEventHook.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_47_StellarForgeEventHook_preAttachCapabilities_AttachCapabilitiesEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:691) [ForgeEventFactory.class:?]
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:679) [ForgeEventFactory.class:?]
	at jeresources.util.FakeClientWorld.<init>(FakeClientWorld.java:43) [FakeClientWorld.class:?]
	at jeresources.compatibility.CompatBase.getWorld(CompatBase.java:21) [CompatBase.class:?]
	at jeresources.compatibility.minecraft.MinecraftCompat.registerVanillaMobs(MinecraftCompat.java:42) [MinecraftCompat.class:?]
	at jeresources.compatibility.minecraft.MinecraftCompat.init(MinecraftCompat.java:34) [MinecraftCompat.class:?]
	at jeresources.compatibility.Compatibility.init(Compatibility.java:26) [Compatibility.class:?]
	at jeresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:14) [CommonProxy.class:?]
	at jeresources.jei.JEIConfig.register(JEIConfig.java:50) [JEIConfig.class:?]
```
