### ISSUE TITLE
JER not working with CraftPresence

### ISSUE THREAD

**Issue by Zeycox** [way2muchnoise/JustEnoughResources#407]
When i click for exemple on gunpowder, it doesn't show the JER menu

[latest.log](https://github.com/way2muchnoise/JustEnoughResources/files/12040577/latest.log)

**Comment by PinkLasagna03** [comment]
I have the same problem, but I have no idea why it doesn't work. Non of the JER features works. 
[latest.log](https://github.com/way2muchnoise/JustEnoughResources/files/12064617/latest.log)

**Comment by generrosity** [comment]
How did you figure that out @Zeycox ?

**Comment by Zeycox** [comment]
> How did you figure that out @Zeycox ?

I launched the game several times by removing mods little by little, everything works fine except when the CraftPresence mod is activated

**Comment by generrosity** [comment]
Removing CraftPresence did seem to help us as well. 

Dont forget you can edit the title of the issue to include CraftPresence so that it gets looked at more

**Comment by CDAGaming** [comment]
You know, I'd really appreciate if people ping me for CraftPresence issues, it really helps speed things along...

As for this, CraftPresence shouldn't be at fault considering:
```
[16:37:15] [CraftPresence/ERROR]: Uncaught exception in thread "CraftPresence"
java.lang.IllegalArgumentException: Multiple entries with same key: moonlight:moonlight/map_markers=net.minecraft.class_7877$class_7885@6d35386c and moonlight:moonlight/map_markers=net.minecraft.class_7877$class_7885@6d35386c
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:377) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:371) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:241) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.RegularImmutableMap.fromEntryArrayCheckingBucketOverflow(RegularImmutableMap.java:132) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:94) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:573) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.buildOrThrow(ImmutableMap.java:601) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:588) ~[guava-31.1-jre.jar:?]
	at net.minecraft.class_7877$class_7878.method_46796(class_7877.java:101) ~[client-intermediary.jar:?]
	at net.minecraft.class_7877.method_46784(class_7877.java:256) ~[client-intermediary.jar:?]
	at net.minecraft.class_7877.method_46780(class_7877.java:262) ~[client-intermediary.jar:?]
	at net.minecraft.class_7887.method_46817(class_7887.java:96) ~[client-intermediary.jar:?]
	at fabric.com.gitlab.cdagaming.craftpresence.utils.world.DimensionUtils.getDimensionTypes(DimensionUtils.java:190) ~[CraftPresence-2.1.2+1.20.1.jar:?]
	at fabric.com.gitlab.cdagaming.craftpresence.utils.world.DimensionUtils.getAllData(DimensionUtils.java:209) ~[CraftPresence-2.1.2+1.20.1.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

This is the exception CraftPresence reports, on the [following line](https://gitlab.com/CDAGaming/CraftPresence/-/blob/1.20.1/common/src/main/java/com/gitlab/cdagaming/craftpresence/utils/world/DimensionUtils.java?ref_type=heads#L190)

However:

```
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: moonlight:moonlight/map_markers=net.minecraft.class_7877$class_7885@727650d6 and moonlight:moonlight/map_markers=net.minecraft.class_7877$class_7885@727650d6
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:377) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:371) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:241) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.RegularImmutableMap.fromEntryArrayCheckingBucketOverflow(RegularImmutableMap.java:132) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:94) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:573) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.buildOrThrow(ImmutableMap.java:601) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:588) ~[guava-31.1-jre.jar:?]
	at net.minecraft.class_7877$class_7878.method_46796(class_7877.java:101) ~[client-intermediary.jar:?]
	at net.minecraft.class_7877.method_46784(class_7877.java:256) ~[client-intermediary.jar:?]
	at net.minecraft.class_7877.method_46780(class_7877.java:262) ~[client-intermediary.jar:?]
	at net.minecraft.class_7887.method_46817(class_7887.java:96) ~[client-intermediary.jar:?]
	at jeresources.api.util.BiomeHelper.getBiome(BiomeHelper.java:20) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.222.jar:?]
	at jeresources.api.restrictions.BiomeRestriction.<init>(BiomeRestriction.java:46) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.222.jar:?]
	at jeresources.api.restrictions.BiomeRestriction.<clinit>(BiomeRestriction.java:19) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.222.jar:?]
	... 30 more
```

This very same exception is also thrown in JustEnoughResources.

Given that my usage is very vanilla-based, I'm more inclined to believe `moonlight` is at fault for this issue (Either that or BOTH our mods are at fault, given the exception threw with or without CraftPresence).
