### ISSUE TITLE
Does not work with Galosphere. Unreferenced key: ResourceKey[minecraft:worldgen/biome / galosphere:crystal_canyons]

### ISSUE THREAD

**Issue by gardenappl** [way2muchnoise/JustEnoughResources#417]
```
[09Sep2023 01:07:18.126] [Render thread/ERROR] [mezz.jei.library.load.PluginCaller/]: Caught an error from mod plugin: class jeresources.jei.JEIConfig minecraft:jeresources
java.lang.ExceptionInInitializerError: null
	at jeresources.api.restrictions.Restriction.<init>(Restriction.java:23) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23151!/:1.4.0.238]
	at jeresources.api.restrictions.Restriction.<clinit>(Restriction.java:6) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23151!/:1.4.0.238]
	at jeresources.compatibility.minecraft.MinecraftCompat.registerOres(MinecraftCompat.java:67) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23151!/:1.4.0.238]
	at jeresources.compatibility.minecraft.MinecraftCompat.init(MinecraftCompat.java:37) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23151!/:1.4.0.238]
	at jeresources.compatibility.Compatibility.init(Compatibility.java:27) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23151!/:1.4.0.238]
	at jeresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:14) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23151!/:1.4.0.238]
	at jeresources.jei.JEIConfig.registerCategories(JEIConfig.java:98) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23151!/:1.4.0.238]
	at mezz.jei.library.load.PluginLoader.lambda$createRecipeCategories$3(PluginLoader.java:90) ~[jei-1.20.1-forge-15.2.0.27.jar%23150!/:15.2.0.27]
	at mezz.jei.library.load.PluginCaller.callOnPlugins(PluginCaller.java:27) ~[jei-1.20.1-forge-15.2.0.27.jar%23150!/:15.2.0.27]
	at mezz.jei.library.load.PluginLoader.createRecipeCategories(PluginLoader.java:90) ~[jei-1.20.1-forge-15.2.0.27.jar%23150!/:15.2.0.27]
	at mezz.jei.library.load.PluginLoader.createRecipeManager(PluginLoader.java:119) ~[jei-1.20.1-forge-15.2.0.27.jar%23150!/:15.2.0.27]
	at mezz.jei.library.startup.JeiStarter.start(JeiStarter.java:132) ~[jei-1.20.1-forge-15.2.0.27.jar%23150!/:15.2.0.27]
	at mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:137) ~[jei-1.20.1-forge-15.2.0.27.jar%23150!/:15.2.0.27]
	at mezz.jei.forge.startup.StartEventObserver.onEvent(StartEventObserver.java:100) ~[jei-1.20.1-forge-15.2.0.27.jar%23150!/:15.2.0.27]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%23127!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%23127!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23127!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23127!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5859_(ClientPacketListener.java:1451) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:35) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:11) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.3.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.3.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) ~[?:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[?:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[?:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[?:?]
Caused by: java.lang.IllegalStateException: Errors during registry creation
	at net.minecraft.core.RegistrySetBuilder$BuildState.m_255178_(RegistrySetBuilder.java:136) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
	at net.minecraft.core.RegistrySetBuilder.m_255144_(RegistrySetBuilder.java:62) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
	at net.minecraft.data.registries.VanillaRegistries.m_255371_(VanillaRegistries.java:72) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
	at jeresources.api.util.BiomeHelper.getBiome(BiomeHelper.java:20) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23151!/:1.4.0.238]
	at jeresources.api.restrictions.BiomeRestriction.<init>(BiomeRestriction.java:46) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23151!/:1.4.0.238]
	at jeresources.api.restrictions.BiomeRestriction.<clinit>(BiomeRestriction.java:19) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23151!/:1.4.0.238]
	... 52 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / galosphere:lichen_caves]
		at net.minecraft.core.RegistrySetBuilder$BuildState.m_255228_(RegistrySetBuilder.java:126) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
		at net.minecraft.core.RegistrySetBuilder.m_255144_(RegistrySetBuilder.java:61) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
		at net.minecraft.data.registries.VanillaRegistries.m_255371_(VanillaRegistries.java:72) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
		at jeresources.api.util.BiomeHelper.getBiome(BiomeHelper.java:20) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23151!/:1.4.0.238]
		at jeresources.api.restrictions.BiomeRestriction.<init>(BiomeRestriction.java:46) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23151!/:1.4.0.238]
		at jeresources.api.restrictions.BiomeRestriction.<clinit>(BiomeRestriction.java:19) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23151!/:1.4.0.238]
		at jeresources.api.restrictions.Restriction.<init>(Restriction.java:23) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23151!/:1.4.0.238]
		at jeresources.api.restrictions.Restriction.<clinit>(Restriction.java:6) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23151!/:1.4.0.238]
		at jeresources.compatibility.minecraft.MinecraftCompat.registerOres(MinecraftCompat.java:67) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23151!/:1.4.0.238]
		at jeresources.compatibility.minecraft.MinecraftCompat.init(MinecraftCompat.java:37) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23151!/:1.4.0.238]
		at jeresources.compatibility.Compatibility.init(Compatibility.java:27) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23151!/:1.4.0.238]
		at jeresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:14) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23151!/:1.4.0.238]
		at jeresources.jei.JEIConfig.registerCategories(JEIConfig.java:98) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23151!/:1.4.0.238]
		at mezz.jei.library.load.PluginLoader.lambda$createRecipeCategories$3(PluginLoader.java:90) ~[jei-1.20.1-forge-15.2.0.27.jar%23150!/:15.2.0.27]
		at mezz.jei.library.load.PluginCaller.callOnPlugins(PluginCaller.java:27) ~[jei-1.20.1-forge-15.2.0.27.jar%23150!/:15.2.0.27]
		at mezz.jei.library.load.PluginLoader.createRecipeCategories(PluginLoader.java:90) ~[jei-1.20.1-forge-15.2.0.27.jar%23150!/:15.2.0.27]
		at mezz.jei.library.load.PluginLoader.createRecipeManager(PluginLoader.java:119) ~[jei-1.20.1-forge-15.2.0.27.jar%23150!/:15.2.0.27]
		at mezz.jei.library.startup.JeiStarter.start(JeiStarter.java:132) ~[jei-1.20.1-forge-15.2.0.27.jar%23150!/:15.2.0.27]
		at mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:137) ~[jei-1.20.1-forge-15.2.0.27.jar%23150!/:15.2.0.27]
		at mezz.jei.forge.startup.StartEventObserver.onEvent(StartEventObserver.java:100) ~[jei-1.20.1-forge-15.2.0.27.jar%23150!/:15.2.0.27]
		at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%23127!/:?]
		at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%23127!/:?]
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23127!/:?]
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23127!/:?]
		at net.minecraft.client.multiplayer.ClientPacketListener.m_5859_(ClientPacketListener.java:1451) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
		at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:35) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
		at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:11) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
		at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
		at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
		at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
		at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
		at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
		at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
		at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
		at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
		at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
		at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
		at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.3.jar:?]
		at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.3.jar:?]
		at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.3.jar:?]
		at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
		at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
		at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
		at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
		at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
		at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
		at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
		at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
		at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) ~[?:?]
		at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[?:?]
		at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[?:?]
		at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[?:?]
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / galosphere:crystal_canyons]
		at net.minecraft.core.RegistrySetBuilder$BuildState.m_255228_(RegistrySetBuilder.java:126) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
		at net.minecraft.core.RegistrySetBuilder.m_255144_(RegistrySetBuilder.java:61) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
		at net.minecraft.data.registries.VanillaRegistries.m_255371_(VanillaRegistries.java:72) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
		at jeresources.api.util.BiomeHelper.getBiome(BiomeHelper.java:20) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23151!/:1.4.0.238]
		at jeresources.api.restrictions.BiomeRestriction.<init>(BiomeRestriction.java:46) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23151!/:1.4.0.238]
		at jeresources.api.restrictions.BiomeRestriction.<clinit>(BiomeRestriction.java:19) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23151!/:1.4.0.238]
		at jeresources.api.restrictions.Restriction.<init>(Restriction.java:23) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23151!/:1.4.0.238]
		at jeresources.api.restrictions.Restriction.<clinit>(Restriction.java:6) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23151!/:1.4.0.238]
		at jeresources.compatibility.minecraft.MinecraftCompat.registerOres(MinecraftCompat.java:67) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23151!/:1.4.0.238]
		at jeresources.compatibility.minecraft.MinecraftCompat.init(MinecraftCompat.java:37) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23151!/:1.4.0.238]
		at jeresources.compatibility.Compatibility.init(Compatibility.java:27) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23151!/:1.4.0.238]
		at jeresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:14) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23151!/:1.4.0.238]
		at jeresources.jei.JEIConfig.registerCategories(JEIConfig.java:98) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23151!/:1.4.0.238]
		at mezz.jei.library.load.PluginLoader.lambda$createRecipeCategories$3(PluginLoader.java:90) ~[jei-1.20.1-forge-15.2.0.27.jar%23150!/:15.2.0.27]
		at mezz.jei.library.load.PluginCaller.callOnPlugins(PluginCaller.java:27) ~[jei-1.20.1-forge-15.2.0.27.jar%23150!/:15.2.0.27]
		at mezz.jei.library.load.PluginLoader.createRecipeCategories(PluginLoader.java:90) ~[jei-1.20.1-forge-15.2.0.27.jar%23150!/:15.2.0.27]
		at mezz.jei.library.load.PluginLoader.createRecipeManager(PluginLoader.java:119) ~[jei-1.20.1-forge-15.2.0.27.jar%23150!/:15.2.0.27]
		at mezz.jei.library.startup.JeiStarter.start(JeiStarter.java:132) ~[jei-1.20.1-forge-15.2.0.27.jar%23150!/:15.2.0.27]
		at mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:137) ~[jei-1.20.1-forge-15.2.0.27.jar%23150!/:15.2.0.27]
		at mezz.jei.forge.startup.StartEventObserver.onEvent(StartEventObserver.java:100) ~[jei-1.20.1-forge-15.2.0.27.jar%23150!/:15.2.0.27]
		at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%23127!/:?]
		at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%23127!/:?]
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23127!/:?]
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23127!/:?]
		at net.minecraft.client.multiplayer.ClientPacketListener.m_5859_(ClientPacketListener.java:1451) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
		at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:35) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
		at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:11) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
		at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
		at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
		at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
		at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
		at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
		at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
		at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23152!/:?]
		at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
		at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
		at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
		at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.3.jar:?]
		at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.3.jar:?]
		at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.3.jar:?]
		at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
		at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
		at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
		at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
		at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
		at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
		at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
		at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
		at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) ~[?:?]
		at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[?:?]
		at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[?:?]
		at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[?:?]
```

**Comment by gardenappl** [comment]
Sorry, should've mentioned. This is Forge, JER 1.4.0.238.

I did test it with just JEI, JER and Galosphere, this totally breaks the plugin. Meanwhile with 300+ mods (but without Galosphere) JER works fine.

**Comment by way2muchnoise** [comment]
Similar issue in #412 but for a different mod

**Comment by Puffadillo** [comment]
Same issue here. I was a bit confused why all the plugins suddenly stopped working, and then I remembered I installed Galosphere.

**Comment by Lonemind** [comment]
I'm also getting this issue.

**Comment by TophC7** [comment]
getting this issue while trying to make a modpack, galosphere as well
