### ISSUE TITLE
JER Villagers tab malfunction bug

### ISSUE THREAD

**Issue by Krutoy242** [way2muchnoise/JustEnoughResources#423]
Opening *Villagers* tab caused error spam and malfunction of tab itself.

How to reproduce:
1. Install only `HEI 4.25.0` + `JER 0.9.3.203`
2. Run game
3. Open JEI tab with villagers
4. See how total numbers of pages in this trade becomes less and less
5. After some scrolling, only 2 bugged trades left

https://github.com/CleanroomMC/HadEnoughItems/assets/936618/cf12b4ee-83cc-463a-bb3a-8a94fa864617

```less
[Client thread/ERROR] [HadEnoughItems]: Error caught from Recipe Category: jeresources.jei.villager.VillagerCategory
java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_352]
	at java.util.LinkedList.get(LinkedList.java:476) ~[?:1.8.0_352]
	at jeresources.entry.VillagerEntry.getVillagerTrades(VillagerEntry.java:37) ~[VillagerEntry.class:?]
	at jeresources.jei.villager.VillagerWrapper.getTrades(VillagerWrapper.java:35) ~[VillagerWrapper.class:?]
	at jeresources.jei.villager.VillagerCategory.setRecipe(VillagerCategory.java:58) ~[VillagerCategory.class:?]
	at jeresources.jei.villager.VillagerCategory.setRecipe(VillagerCategory.java:16) ~[VillagerCategory.class:?]
	at mezz.jei.gui.recipes.RecipeLayout.create(RecipeLayout.java:69) [RecipeLayout.class:?]
	at mezz.jei.gui.recipes.RecipeGuiLogic.getRecipeLayouts(RecipeGuiLogic.java:198) [RecipeGuiLogic.class:?]
	at mezz.jei.gui.recipes.RecipesGui.updateLayout(RecipesGui.java:492) [RecipesGui.class:?]
	at mezz.jei.gui.recipes.RecipesGui.onStateChange(RecipesGui.java:538) [RecipesGui.class:?]
	at mezz.jei.gui.recipes.RecipeGuiLogic.nextPage(RecipeGuiLogic.java:254) [RecipeGuiLogic.class:?]
	at mezz.jei.gui.recipes.RecipesGui.func_146284_a(RecipesGui.java:438) [RecipesGui.class:?]
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443) [blk.class:?]
	at mezz.jei.gui.recipes.RecipesGui.func_73864_a(RecipesGui.java:336) [RecipesGui.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533) [blk.class:?]
	at mezz.jei.gui.recipes.RecipesGui.func_146274_d(RecipesGui.java:304) [RecipesGui.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501) [blk.class:?]
```

[debug.log](https://github.com/CleanroomMC/HadEnoughItems/files/12817907/debug.log)

**Comment by Romz24** [comment]
The problem is still relevant

```
[19:53:04] [Client thread/ERROR] [Had Enough Items]: Error caught from Recipe Category: jeresources.jei.villager.VillagerCategory
java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.LinkedList.checkElementIndex(Unknown Source)
	at java.util.LinkedList.get(Unknown Source)
	at jeresources.entry.VillagerEntry.getVillagerTrades(VillagerEntry.java:37)
	at jeresources.jei.villager.VillagerWrapper.getTrades(VillagerWrapper.java:35)
	at jeresources.jei.villager.VillagerCategory.setRecipe(VillagerCategory.java:58)
	at jeresources.jei.villager.VillagerCategory.setRecipe(VillagerCategory.java:16)
	at mezz.jei.gui.recipes.RecipeLayout.create(RecipeLayout.java:79)
	at mezz.jei.gui.recipes.RecipeGuiLogic.getRecipeLayouts(RecipeGuiLogic.java:307)
	at mezz.jei.gui.recipes.RecipesGui.updateLayout(RecipesGui.java:592)
	at mezz.jei.gui.recipes.RecipesGui.onStateChange(RecipesGui.java:661)
	at mezz.jei.gui.recipes.RecipeGuiLogic.setRecipeCategory(RecipeGuiLogic.java:347)
	at mezz.jei.gui.recipes.RecipeCategoryTab.handleMouseClicked(RecipeCategoryTab.java:39)
	at mezz.jei.gui.recipes.RecipeGuiTabs.handleMouseClicked(RecipeGuiTabs.java:133)
	at mezz.jei.gui.recipes.RecipesGui.mouseClicked(RecipesGui.java:389)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:536)
	at mezz.jei.gui.recipes.RecipesGui.handleMouseInput(RecipesGui.java:349)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:504)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1771)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
	at net.minecraft.client.Minecraft.run(Minecraft.java:9164)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at top.outlands.foundation.LaunchHandler.launch(LaunchHandler.java:125)
	at top.outlands.foundation.boot.Foundation.main(Foundation.java:43)
	at com.cleanroommc.relauncher.wrapper.RelaunchMainWrapper.main(RelaunchMainWrapper.java:20)
```

**Comment by Romz24** [comment]
I compared versions `0.9.2.60` and `0.9.3.203` and identified the changes that are causing this issue. If those changes are reverted, the problem disappears. Commit link:  https://github.com/way2muchnoise/JustEnoughResources/commit/52718d97d0f21150f8cae6debae8bd4254bfa665

- VillagerEntry.java
<img width="808" height="87" alt="Image" src="https://github.com/user-attachments/assets/400f48df-4cd2-47f6-a406-dad98a9051bf" />

- VillagerWrapper.java
<img width="644" height="123" alt="Image" src="https://github.com/user-attachments/assets/34546e66-a967-40c8-a47d-5a6104f3045b" />
