### ISSUE TITLE
[1.20.4] jer got killed silently

### ISSUE THREAD

**Issue by younggam** [way2muchnoise/JustEnoughResources#459]
full log:
[latest.log](https://github.com/way2muchnoise/JustEnoughResources/files/14334371/latest.log)
```
[00:34:10] [Render thread/ERROR]: Caught an error from mod plugin: class jeresources.jei.JEIConfig minecraft:jeresources
java.lang.NoSuchFieldError: field_943
	at jeresources.platform.ILootTableHelper.getPools(ILootTableHelper.java:14) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
	at jeresources.util.LootTableHelper.getPools(LootTableHelper.java:56) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
	at jeresources.util.LootTableHelper.toDrops(LootTableHelper.java:72) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
	at jeresources.util.LootTableHelper.toDrops(LootTableHelper.java:95) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
	at jeresources.util.PlantHelper.getSeeds(PlantHelper.java:14) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
	at jeresources.entry.PlantEntry.registerGrass(PlantEntry.java:28) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
	at jeresources.registry.PlantRegistry.<init>(PlantRegistry.java:25) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
	at jeresources.registry.PlantRegistry.getInstance(PlantRegistry.java:19) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
	at jeresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:11) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
	at jeresources.jei.JEIConfig.registerCategories(JEIConfig.java:98) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
	at mezz.jei.library.load.PluginLoader.lambda$createRecipeCategories$4(PluginLoader.java:97) ~[jei-1.20.4-fabric-17.3.0.49.jar:?]
	at mezz.jei.library.load.PluginCaller.callOnPlugins(PluginCaller.java:27) ~[jei-1.20.4-fabric-17.3.0.49.jar:?]
	at mezz.jei.library.load.PluginLoader.createRecipeCategories(PluginLoader.java:97) ~[jei-1.20.4-fabric-17.3.0.49.jar:?]
	at mezz.jei.library.load.PluginLoader.createRecipeManager(PluginLoader.java:126) ~[jei-1.20.4-fabric-17.3.0.49.jar:?]
	at mezz.jei.library.startup.JeiStarter.start(JeiStarter.java:132) ~[jei-1.20.4-fabric-17.3.0.49.jar:?]
	at mezz.jei.fabric.startup.ClientLifecycleHandler.startJei(ClientLifecycleHandler.java:84) ~[jei-1.20.4-fabric-17.3.0.49.jar:?]
	at mezz.jei.fabric.startup.ClientLifecycleHandler.lambda$registerEvents$1(ClientLifecycleHandler.java:53) ~[jei-1.20.4-fabric-17.3.0.49.jar:?]
	at mezz.jei.fabric.events.JeiLifecycleEvents.lambda$static$4(JeiLifecycleEvents.java:28) ~[jei-1.20.4-fabric-17.3.0.49.jar:?]
	at net.minecraft.class_634.handler$bfc001$jei$handleUpdateRecipes(class_634.java:5943) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11106(class_634.java:1442) ~[client-intermediary.jar:?]
	at net.minecraft.class_2788.method_11997(class_2788.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_2788.method_11054(class_2788.java:15) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:24) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1283) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[fabric-loader-0.15.7-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]```

**Comment by way2muchnoise** [comment]
Kind of strange that it would break on a field error, can you share MC/Fabric versions used as well? I see 1.20.1-1.4.0.247 as JER version.

**Comment by younggam** [comment]
I have used 0.96.3 + 1.20.4 which is the latest.
maybe it is just version compatibility issue?
rer also got crashed.

**Comment by way2muchnoise** [comment]
Actual 1.20.4 builds are now available as alpha

https://modrinth.com/mod/just-enough-resources-jer/versions?g=1.20.4

https://legacy.curseforge.com/minecraft/mc-mods/just-enough-resources-jer/files/all?filter-status=1&filter-game-version=2020709689%3A10407
