### ISSUE TITLE
Not working at all 1.20.1

### ISSUE THREAD

**Issue by ArticulatedDrunk** [way2muchnoise/JustEnoughResources#469]
[latest.log](https://github.com/way2muchnoise/JustEnoughResources/files/14596825/latest.log)
We had a lot of trouble with region scanner and when we finally got an output jer is still not working at all. 
Hopefully we can figure out the issue or get it fixed soon. But I don't even understand why region scanner is necessary, this used to just be pulled from the world gen code or something.

**Comment by uhloin** [comment]
I have no JER tabs (1.20.1 forge)
May be this log will help
[latest.log](https://github.com/way2muchnoise/JustEnoughResources/files/14618133/latest.log)

**Comment by ponduzn** [comment]
Can confirm, not working in 1.20.1 for me either.

> [01:52:57] [Render thread/ERROR]: Caught an error from mod plugin: class jeresources.jei.JEIConfig minecraft:jeresources
java.lang.ExceptionInInitializerError: null
	at jeresources.api.restrictions.Restriction.<init>(Restriction.java:23) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
	at jeresources.api.restrictions.Restriction.<clinit>(Restriction.java:6) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
	at jeresources.compatibility.minecraft.MinecraftCompat.registerOres(MinecraftCompat.java:67) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
	at jeresources.compatibility.minecraft.MinecraftCompat.init(MinecraftCompat.java:37) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
	at jeresources.compatibility.Compatibility.init(Compatibility.java:27) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
	at jeresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:14) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
	at jeresources.jei.JEIConfig.registerCategories(JEIConfig.java:98) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
	at mezz.jei.library.load.PluginLoader.lambda$createRecipeCategories$3(PluginLoader.java:91) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
	at mezz.jei.library.load.PluginCaller.callOnPlugins(PluginCaller.java:27) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
	at mezz.jei.library.load.PluginLoader.createRecipeCategories(PluginLoader.java:91) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
	at mezz.jei.library.load.PluginLoader.createRecipeManager(PluginLoader.java:120) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
	at mezz.jei.library.startup.JeiStarter.start(JeiStarter.java:132) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
	at mezz.jei.fabric.startup.ClientLifecycleHandler.startJei(ClientLifecycleHandler.java:84) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
	at mezz.jei.fabric.startup.ClientLifecycleHandler.lambda$registerEvents$1(ClientLifecycleHandler.java:53) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
	at mezz.jei.fabric.events.JeiLifecycleEvents.lambda$static$4(JeiLifecycleEvents.java:28) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
	at net.minecraft.class_634.handler$dei003$jei$handleUpdateRecipes(class_634.java:11222) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11106(class_634.java:1445) ~[client-intermediary.jar:?]
	at net.minecraft.class_2788.method_11997(class_2788.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_2788.method_11054(class_2788.java:14) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[fabric-loader-0.15.7-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
Caused by: java.lang.IllegalStateException: Errors during registry creation
	at net.minecraft.class_7877$class_7878.method_46798(class_7877.java:137) ~[client-intermediary.jar:?]
	at net.minecraft.class_7877.method_46780(class_7877.java:269) ~[client-intermediary.jar:?]
	at net.minecraft.class_7887.method_46817(class_7887.java:96) ~[client-intermediary.jar:?]
	at jeresources.api.util.BiomeHelper.getBiome(BiomeHelper.java:20) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
	at jeresources.api.restrictions.BiomeRestriction.<init>(BiomeRestriction.java:46) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
	at jeresources.api.restrictions.BiomeRestriction.<clinit>(BiomeRestriction.java:19) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
	... 30 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / riverredux:gravelly_river]
		at net.minecraft.class_7877$class_7878.method_46797(class_7877.java:128) ~[client-intermediary.jar:?]
		at net.minecraft.class_7877.method_46780(class_7877.java:268) ~[client-intermediary.jar:?]
		at net.minecraft.class_7887.method_46817(class_7887.java:96) ~[client-intermediary.jar:?]
		at jeresources.api.util.BiomeHelper.getBiome(BiomeHelper.java:20) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
		at jeresources.api.restrictions.BiomeRestriction.<init>(BiomeRestriction.java:46) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
		at jeresources.api.restrictions.BiomeRestriction.<clinit>(BiomeRestriction.java:19) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
		at jeresources.api.restrictions.Restriction.<init>(Restriction.java:23) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
		at jeresources.api.restrictions.Restriction.<clinit>(Restriction.java:6) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
		at jeresources.compatibility.minecraft.MinecraftCompat.registerOres(MinecraftCompat.java:67) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
		at jeresources.compatibility.minecraft.MinecraftCompat.init(MinecraftCompat.java:37) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
		at jeresources.compatibility.Compatibility.init(Compatibility.java:27) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
		at jeresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:14) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
		at jeresources.jei.JEIConfig.registerCategories(JEIConfig.java:98) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
		at mezz.jei.library.load.PluginLoader.lambda$createRecipeCategories$3(PluginLoader.java:91) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
		at mezz.jei.library.load.PluginCaller.callOnPlugins(PluginCaller.java:27) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
		at mezz.jei.library.load.PluginLoader.createRecipeCategories(PluginLoader.java:91) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
		at mezz.jei.library.load.PluginLoader.createRecipeManager(PluginLoader.java:120) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
		at mezz.jei.library.startup.JeiStarter.start(JeiStarter.java:132) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
		at mezz.jei.fabric.startup.ClientLifecycleHandler.startJei(ClientLifecycleHandler.java:84) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
		at mezz.jei.fabric.startup.ClientLifecycleHandler.lambda$registerEvents$1(ClientLifecycleHandler.java:53) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
		at mezz.jei.fabric.events.JeiLifecycleEvents.lambda$static$4(JeiLifecycleEvents.java:28) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
		at net.minecraft.class_634.handler$dei003$jei$handleUpdateRecipes(class_634.java:11222) ~[client-intermediary.jar:?]
		at net.minecraft.class_634.method_11106(class_634.java:1445) ~[client-intermediary.jar:?]
		at net.minecraft.class_2788.method_11997(class_2788.java:32) ~[client-intermediary.jar:?]
		at net.minecraft.class_2788.method_11054(class_2788.java:14) ~[client-intermediary.jar:?]
		at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
		at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
		at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
		at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
		at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
		at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
		at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
		at net.minecraft.client.main.Main.main(Main.java:250) ~[fabric-loader-0.15.7-1.20.1.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / riverredux:sandy_river]
		at net.minecraft.class_7877$class_7878.method_46797(class_7877.java:128) ~[client-intermediary.jar:?]
		at net.minecraft.class_7877.method_46780(class_7877.java:268) ~[client-intermediary.jar:?]
		at net.minecraft.class_7887.method_46817(class_7887.java:96) ~[client-intermediary.jar:?]
		at jeresources.api.util.BiomeHelper.getBiome(BiomeHelper.java:20) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
		at jeresources.api.restrictions.BiomeRestriction.<init>(BiomeRestriction.java:46) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
		at jeresources.api.restrictions.BiomeRestriction.<clinit>(BiomeRestriction.java:19) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
		at jeresources.api.restrictions.Restriction.<init>(Restriction.java:23) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
		at jeresources.api.restrictions.Restriction.<clinit>(Restriction.java:6) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
		at jeresources.compatibility.minecraft.MinecraftCompat.registerOres(MinecraftCompat.java:67) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
		at jeresources.compatibility.minecraft.MinecraftCompat.init(MinecraftCompat.java:37) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
		at jeresources.compatibility.Compatibility.init(Compatibility.java:27) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
		at jeresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:14) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
		at jeresources.jei.JEIConfig.registerCategories(JEIConfig.java:98) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
		at mezz.jei.library.load.PluginLoader.lambda$createRecipeCategories$3(PluginLoader.java:91) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
		at mezz.jei.library.load.PluginCaller.callOnPlugins(PluginCaller.java:27) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
		at mezz.jei.library.load.PluginLoader.createRecipeCategories(PluginLoader.java:91) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
		at mezz.jei.library.load.PluginLoader.createRecipeManager(PluginLoader.java:120) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
		at mezz.jei.library.startup.JeiStarter.start(JeiStarter.java:132) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
		at mezz.jei.fabric.startup.ClientLifecycleHandler.startJei(ClientLifecycleHandler.java:84) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
		at mezz.jei.fabric.startup.ClientLifecycleHandler.lambda$registerEvents$1(ClientLifecycleHandler.java:53) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
		at mezz.jei.fabric.events.JeiLifecycleEvents.lambda$static$4(JeiLifecycleEvents.java:28) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
		at net.minecraft.class_634.handler$dei003$jei$handleUpdateRecipes(class_634.java:11222) ~[client-intermediary.jar:?]
		at net.minecraft.class_634.method_11106(class_634.java:1445) ~[client-intermediary.jar:?]
		at net.minecraft.class_2788.method_11997(class_2788.java:32) ~[client-intermediary.jar:?]
		at net.minecraft.class_2788.method_11054(class_2788.java:14) ~[client-intermediary.jar:?]
		at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
		at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
		at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
		at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
		at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
		at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
		at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
		at net.minecraft.client.main.Main.main(Main.java:250) ~[fabric-loader-0.15.7-1.20.1.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / riverredux:tropical_river]
		at net.minecraft.class_7877$class_7878.method_46797(class_7877.java:128) ~[client-intermediary.jar:?]
		at net.minecraft.class_7877.method_46780(class_7877.java:268) ~[client-intermediary.jar:?]
		at net.minecraft.class_7887.method_46817(class_7887.java:96) ~[client-intermediary.jar:?]
		at jeresources.api.util.BiomeHelper.getBiome(BiomeHelper.java:20) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
		at jeresources.api.restrictions.BiomeRestriction.<init>(BiomeRestriction.java:46) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
		at jeresources.api.restrictions.BiomeRestriction.<clinit>(BiomeRestriction.java:19) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
		at jeresources.api.restrictions.Restriction.<init>(Restriction.java:23) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
		at jeresources.api.restrictions.Restriction.<clinit>(Restriction.java:6) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
		at jeresources.compatibility.minecraft.MinecraftCompat.registerOres(MinecraftCompat.java:67) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
		at jeresources.compatibility.minecraft.MinecraftCompat.init(MinecraftCompat.java:37) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
		at jeresources.compatibility.Compatibility.init(Compatibility.java:27) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
		at jeresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:14) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
		at jeresources.jei.JEIConfig.registerCategories(JEIConfig.java:98) ~[JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar:?]
		at mezz.jei.library.load.PluginLoader.lambda$createRecipeCategories$3(PluginLoader.java:91) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
		at mezz.jei.library.load.PluginCaller.callOnPlugins(PluginCaller.java:27) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
		at mezz.jei.library.load.PluginLoader.createRecipeCategories(PluginLoader.java:91) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
		at mezz.jei.library.load.PluginLoader.createRecipeManager(PluginLoader.java:120) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
		at mezz.jei.library.startup.JeiStarter.start(JeiStarter.java:132) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
		at mezz.jei.fabric.startup.ClientLifecycleHandler.startJei(ClientLifecycleHandler.java:84) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
		at mezz.jei.fabric.startup.ClientLifecycleHandler.lambda$registerEvents$1(ClientLifecycleHandler.java:53) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
		at mezz.jei.fabric.events.JeiLifecycleEvents.lambda$static$4(JeiLifecycleEvents.java:28) ~[jei-1.20.1-fabric-15.3.0.4.jar:?]
		at net.minecraft.class_634.handler$dei003$jei$handleUpdateRecipes(class_634.java:11222) ~[client-intermediary.jar:?]
		at net.minecraft.class_634.method_11106(class_634.java:1445) ~[client-intermediary.jar:?]
		at net.minecraft.class_2788.method_11997(class_2788.java:32) ~[client-intermediary.jar:?]
		at net.minecraft.class_2788.method_11054(class_2788.java:14) ~[client-intermediary.jar:?]
		at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
		at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
		at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
		at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
		at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
		at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
		at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
		at net.minecraft.client.main.Main.main(Main.java:250) ~[fabric-loader-0.15.7-1.20.1.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]

**Comment by PeglinX** [comment]
I have the same issue

**Comment by drakray** [comment]
Got a similar error with [Galosphere](https://legacy.curseforge.com/minecraft/mc-mods/galosphere/files/4983871) and [TrailsAndTalesPlus](https://legacy.curseforge.com/minecraft/mc-mods/trails-and-tales/files/5045548), on NeoForge 47.1.104 for 1.20.1, where the error logs the mod's biomes

**Comment by monkeybee11** [comment]
same here ive installed the fabric verion and no tabs in JEI for anything this mod shoud be giving things for D:

JER 1.4.0.247 for minecraft 1.20.1

JEI 15.3.0.4 for Fabric 1.20.1
![image](https://github.com/way2muchnoise/JustEnoughResources/assets/1711586/d82298a2-a7fb-4ef1-b32a-e9c96ca53f60)

**Comment by Raeffi** [comment]
Got the same error for GoodEnding Biomes:
`	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / goodending:marshy_swamp]
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / goodending:oak_hammock_forest]
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / goodending:marshy_swamp]`

**Comment by ImVelzee** [comment]
I am facing the same issue on 1.21.1 on Neoforge. Just spent the time installing and preforming the pregen to generate a custom worldgen for the Direwolf20 1.12 modpack, only for nothing to show up after moving the worldgen to the config folder and double checking that DIY is enabled, besides the vanilla ores. I am not sure what, if anything, i am doing wrong. the mod page describes all the steps i took, and yet none of the results look like anything from the documentation.
