### ISSUE TITLE
Forge-1.16.5-0.12.2.216 “Found a broken recipe”“NullPointerException”and Causing the game to become unresponsive？

### ISSUE THREAD

**Issue by Huan-zhaojun** [way2muchnoise/JustEnoughResources#480]
I made a my mod that added an entity, and then found an issue with this JER mod that caused the game to become unresponsive.
### These are the codes for me to add entities：
[Entity](https://github.com/Huan-zhaojun/IFScience/tree/ef17a4c170f200cb8f2834512ec4099423f69a5b/src/main/java/com/ddhuan/ifscience/common/Entity)
[entityTypeRegistry](https://github.com/Huan-zhaojun/IFScience/blob/ef17a4c170f200cb8f2834512ec4099423f69a5b/src/main/java/com/ddhuan/ifscience/common/Entity/entityTypeRegistry.java)

### This is a brief error message：
`[18:07:45] [Render thread/ERROR]: Found a broken recipe: jeresources.jei.mob.MobWrapper@5d6444f9
Failed to get ingredients from recipe wrapper
java.lang.NullPointerException: null
	at jeresources.jei.mob.MobWrapper.getSpawnEgg(MobWrapper.java:168) ~[jeresources:0.12.2.216]`

### My thoughts：
**The entity I added does not have any spawning egg or drop recipe. Is this the cause of the problem?
Between my mod and this JER mod, if I uninstall either one, the game not appear unresponsive.
_However, I uninstalled other mods, leaving only "JEI" and "JER". When creating a new world, I still encountered the error message "Found a broken recipe，although error occurs, the game not become unresponsive._**

### Specific error codes：
`[18:07:45] [Render thread/ERROR]: Found a broken recipe: jeresources.jei.mob.MobWrapper@5d6444f9
Failed to get ingredients from recipe wrapper
java.lang.NullPointerException: null
	at jeresources.jei.mob.MobWrapper.getSpawnEgg(MobWrapper.java:168) ~[jeresources:0.12.2.216]
	at jeresources.jei.mob.MobWrapper.setIngredients(MobWrapper.java:56) ~[jeresources:0.12.2.216]
	at jeresources.jei.BlankJEIRecipeCategory.setIngredients(BlankJEIRecipeCategory.java:28) ~[jeresources:0.12.2.216]
	at jeresources.jei.BlankJEIRecipeCategory.setIngredients(BlankJEIRecipeCategory.java:13) ~[jeresources:0.12.2.216]
	at mezz.jei.recipes.RecipeManagerInternal.addRecipe(RecipeManagerInternal.java:122) ~[jei:7.8.0.1011]
	at mezz.jei.recipes.RecipeManagerInternal.addRecipeTyped(RecipeManagerInternal.java:101) ~[jei:7.8.0.1011]
	at mezz.jei.recipes.RecipeManagerInternal.addRecipes(RecipeManagerInternal.java:94) ~[jei:7.8.0.1011]
	at mezz.jei.recipes.RecipeManagerInternal.<init>(RecipeManagerInternal.java:86) ~[jei:7.8.0.1011]
	at mezz.jei.load.PluginLoader.getRecipeManager(PluginLoader.java:145) ~[jei:7.8.0.1011]
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:74) ~[jei:7.8.0.1011]
	at mezz.jei.startup.ClientLifecycleHandler.startJEI(ClientLifecycleHandler.java:147) ~[jei:7.8.0.1011]
	at mezz.jei.startup.ClientLifecycleHandler.setupJEI(ClientLifecycleHandler.java:140) ~[jei:7.8.0.1011]
	at mezz.jei.startup.ClientLifecycleHandler.lambda$new$3(ClientLifecycleHandler.java:106) ~[jei:7.8.0.1011]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.client.ForgeHooksClient.onRecipesUpdated(ForgeHooksClient.java:772) ~[forge:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_199525_a(ClientPlayNetHandler.java:1315) ~[?:?]
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:27) ~[?:?]
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:15) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:948) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) ~[forge-1.16.5-36.2.41.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]`
### Complete error file：
[minecraft-exported-crash-info-2024-05-01T18-13-48.zip](https://github.com/way2muchnoise/JustEnoughResources/files/15176420/minecraft-exported-crash-info-2024-05-01T18-13-48.zip)

**Comment by Deepfriedyag** [comment]
Am getting the same error in 1.16.5 with mods

**Comment by RConTRS** [comment]
same here

**Comment by way2muchnoise** [comment]
1.16 is no longer supported
