### ISSUE TITLE
MC 1.20.4 Forge 49.1.0 JER not showing up

### ISSUE THREAD

**Issue by 1143910315** [way2muchnoise/JustEnoughResources#490]
[216月2024 02:15:56.071] [Render thread/ERROR] [mezz.jei.library.load.PluginCaller/]: Caught an error from mod plugin: class jeresources.jei.JEIConfig minecraft:jeresources
java.lang.NoClassDefFoundError: net/minecraft/class_1935
	at jeresources.util.LootTableHelper.lambda$toDrops$5(LootTableHelper.java:80) ~[JustEnoughResources-Forge-1.20.4-1.5.0.4.jar!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.Collections$2.tryAdvance(Collections.java:4853) ~[?:?]
	at java.util.Collections$2.forEachRemaining(Collections.java:4861) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at jeresources.util.LootTableHelper.lambda$toDrops$10(LootTableHelper.java:82) ~[JustEnoughResources-Forge-1.20.4-1.5.0.4.jar!/:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at jeresources.util.LootTableHelper.toDrops(LootTableHelper.java:72) ~[JustEnoughResources-Forge-1.20.4-1.5.0.4.jar!/:?]
	at jeresources.entry.MobEntry.create(MobEntry.java:67) ~[JustEnoughResources-Forge-1.20.4-1.5.0.4.jar!/:?]
	at jeresources.compatibility.minecraft.MinecraftCompat.lambda$registerVanillaMobs$0(MinecraftCompat.java:45) ~[JustEnoughResources-Forge-1.20.4-1.5.0.4.jar!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at jeresources.compatibility.minecraft.MinecraftCompat.registerVanillaMobs(MinecraftCompat.java:46) ~[JustEnoughResources-Forge-1.20.4-1.5.0.4.jar!/:?]
	at jeresources.compatibility.minecraft.MinecraftCompat.init(MinecraftCompat.java:34) ~[JustEnoughResources-Forge-1.20.4-1.5.0.4.jar!/:?]
	at jeresources.compatibility.Compatibility.init(Compatibility.java:27) ~[JustEnoughResources-Forge-1.20.4-1.5.0.4.jar!/:?]
	at jeresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:14) ~[JustEnoughResources-Forge-1.20.4-1.5.0.4.jar!/:?]
	at jeresources.jei.JEIConfig.registerCategories(JEIConfig.java:98) ~[JustEnoughResources-Forge-1.20.4-1.5.0.4.jar!/:?]
	at mezz.jei.library.load.PluginLoader.lambda$createRecipeCategories$4(PluginLoader.java:97) ~[jei-1.20.4-forge-17.3.0.1.jar!/:17.3.0.1]
	at mezz.jei.library.load.PluginCaller.callOnPlugins(PluginCaller.java:27) ~[jei-1.20.4-forge-17.3.0.1.jar!/:17.3.0.1]
	at mezz.jei.library.load.PluginLoader.createRecipeCategories(PluginLoader.java:97) ~[jei-1.20.4-forge-17.3.0.1.jar!/:17.3.0.1]
	at mezz.jei.library.load.PluginLoader.createRecipeManager(PluginLoader.java:126) ~[jei-1.20.4-forge-17.3.0.1.jar!/:17.3.0.1]
	at mezz.jei.library.startup.JeiStarter.start(JeiStarter.java:132) ~[jei-1.20.4-forge-17.3.0.1.jar!/:17.3.0.1]
	at mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:137) ~[jei-1.20.4-forge-17.3.0.1.jar!/:17.3.0.1]
	at mezz.jei.forge.startup.StartEventObserver.onEvent(StartEventObserver.java:105) ~[jei-1.20.4-forge-17.3.0.1.jar!/:17.3.0.1]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:245) ~[eventbus-6.2.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:237) ~[eventbus-6.2.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:300) ~[eventbus-6.2.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:281) ~[eventbus-6.2.0.jar:?]
	at net.minecraftforge.client.ForgeHooksClient.onRecipesUpdated(ForgeHooksClient.java:600) ~[forge-1.20.4-49.1.0-universal.jar:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_6327_(ClientPacketListener.java:1336) ~[forge-1.20.4-49.1.0-client.jar:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.m_5797_(ClientboundUpdateRecipesPacket.java:33) ~[forge-1.20.4-49.1.0-client.jar:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.m_5797_(ClientboundUpdateRecipesPacket.java:15) ~[forge-1.20.4-49.1.0-client.jar:?]
	at net.minecraft.network.protocol.PacketUtils.m_304213_(PacketUtils.java:24) ~[forge-1.20.4-49.1.0-client.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[forge-1.20.4-49.1.0-client.jar:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[forge-1.20.4-49.1.0-client.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[forge-1.20.4-49.1.0-client.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[forge-1.20.4-49.1.0-client.jar:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1210) ~[forge-1.20.4-49.1.0-client.jar:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:801) ~[forge-1.20.4-49.1.0-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:234) ~[forge-1.20.4-49.1.0-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:91) ~[fmlloader-1.20.4-49.1.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:75) ~[fmlloader-1.20.4-49.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) ~[modlauncher-10.1.2.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:74) ~[modlauncher-10.1.2.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:114) ~[modlauncher-10.1.2.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:73) ~[modlauncher-10.1.2.jar:?]
	at cpw.mods.modlauncher.BootstrapEntry.main(BootstrapEntry.java:17) ~[modlauncher-10.1.2.jar:?]
	at net.minecraftforge.bootstrap.Bootstrap.moduleMain(Bootstrap.java:188) ~[bootstrap-2.1.0.jar:2.1.0]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.bootstrap.Bootstrap.bootstrapMain(Bootstrap.java:133) ~[bootstrap-2.1.0.jar:2.1.0]
	at net.minecraftforge.bootstrap.Bootstrap.start(Bootstrap.java:53) ~[bootstrap-2.1.0.jar:2.1.0]
	at net.minecraftforge.bootstrap.ForgeBootstrap.main(ForgeBootstrap.java:19) ~[bootstrap-2.1.0.jar:2.1.0]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71) ~[JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) ~[JavaWrapper.jar:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1935
	at net.minecraftforge.securemodules.SecureModuleClassLoader.loadClass(SecureModuleClassLoader.java:447) ~[securemodules-2.2.10.jar!/:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	... 78 more

**Comment by 1143910315** [comment]
When playing on the vanilla server of Minecraft, I discovered that JustEnoughResources lacked a crafting table. After reviewing the debug.log, I came across this section of the error log.
