### ISSUE TITLE
:[Bug]: 1.21.1 Neoforge DIY World Gen

### ISSUE THREAD

**Issue by manmaed** [way2muchnoise/JustEnoughResources#514]
Mods:
Neo: 21.0.146
JEI: 19.8.2.99
JER: 1.6.0.local (In dev env as of commit: https://github.com/way2muchnoise/JustEnoughResources/commit/210cee03995cc21f2111b6212547960c9e9bbfff)

unable to load diy world gen

Debug:
https://pste.me/@2vf4ThzwPQk

[world-gen json](https://pste.me/@un-tCamC_g4)

**Comment by Darwin-Gabriel** [comment]
how do you get the 1.21.1 working?

**Comment by manmaed** [comment]
found the neoforge jar in the 1.21 action [here](https://github.com/way2muchnoise/JustEnoughResources/actions/runs/10546853806)

**Comment by Darwin-Gabriel** [comment]
can you add me on discord bielhiss?

**Comment by manmaed** [comment]
the mod didn't work it as it  didn't show anything

**Comment by Darwin-Gabriel** [comment]
oh ok

**Comment by manmaed** [comment]
have updated urls to use the dev env info

**Comment by way2muchnoise** [comment]
This is why I haven't released a version for Forge or NeoForge on 1.21+, need to figure out what is going on.

```
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.level.ItemLike
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:216) ~[securejarhandler-3.0.8.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 67 more
```

**Comment by way2muchnoise** [comment]
As of 768639a3fb08b5abca1fc0b236e4a1523efe0822, 1.21 version are out for Forge and NeoForge
