### ISSUE TITLE
Incompatibility with forge 1863

### ISSUE THREAD

**Issue by jriwanek** [way2muchnoise/JustEnoughResources#55]
[16:22:13] [Client thread/ERROR] [JEI/]: Failed to register mod plugin: class jeresources.jei.JEIConfig
net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToAccessFieldException: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: DEFAULT_TRADE_LIST_MAP
	at net.minecraftforge.fml.relauncher.ReflectionHelper.getPrivateValue(ReflectionHelper.java:117) ~[forge-1.9-12.16.0.1863-1.9.jar:?]
	at jeresources.util.TradeHelper.getTrades(TradeHelper.java:9) ~[TradeHelper.class:?]
	at jeresources.registry.VillagerRegistry.<init>(VillagerRegistry.java:28) ~[VillagerRegistry.class:?]
	at jeresources.registry.VillagerRegistry.getInstance(VillagerRegistry.java:19) ~[VillagerRegistry.class:?]
	at jeresources.jei.JEIConfig.register(JEIConfig.java:46) ~[JEIConfig.class:?]
	at mezz.jei.ProxyCommonClient.startJEI(ProxyCommonClient.java:161) [ProxyCommonClient.class:?]
	at mezz.jei.ProxyCommonClient.onEntityJoinedWorld(ProxyCommonClient.java:137) [ProxyCommonClient.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_196_ProxyCommonClient_onEntityJoinedWorld_EntityJoinWorldEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at net.minecraft.world.World.func_72838_d(World.java:1111) [aht.class:?]
	at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:193) [bku.class:?]
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2438) [bcf.class:?]
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2346) [bcf.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:272) [bks.class:?]
	at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:76) [gs.class:?]
	at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:13) [gs.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_77]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_77]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [g.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1041) [bcf.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366) [bcf.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_77]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: DEFAULT_TRADE_LIST_MAP
	at net.minecraftforge.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:90) ~[forge-1.9-12.16.0.1863-1.9.jar:?]
	at net.minecraftforge.fml.relauncher.ReflectionHelper.getPrivateValue(ReflectionHelper.java:113) ~[forge-1.9-12.16.0.1863-1.9.jar:?]
	... 29 more
Caused by: java.lang.NoSuchFieldException: DEFAULT_TRADE_LIST_MAP
	at java.lang.Class.getDeclaredField(Unknown Source) ~[?:1.8.0_77]
	at net.minecraftforge.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:81) ~[forge-1.9-12.16.0.1863-1.9.jar:?]
	at net.minecraftforge.fml.relauncher.ReflectionHelper.getPrivateValue(ReflectionHelper.java:113) ~[forge-1.9-12.16.0.1863-1.9.jar:?]
	... 29 more

**Comment by Lanse505** [comment]
@mezz @way2muchnoise 

Can confirm this issue pops-up in my dev pack for 1.9 using forge 1863
http://puu.sh/odSe1/e3f7bafdd0.log

**Comment by Lanse505** [comment]
Towards the End:

Also Cleaner Log:
http://puu.sh/odSj7/5bf0ad3b38.txt

**Comment by mezz** [comment]
No need to ping me, please just wait for Way to update.

**Comment by way2muchnoise** [comment]
Can you test the latest build from the [build server](https://drone.io/github.com/way2muchnoise/JustEnoughResources/files)?

**Comment by Lanse505** [comment]
Works with the latest build @way2muchnoise
