### ISSUE TITLE
All recipe types (like OreGen) are completly empty in dev env

### ISSUE THREAD

**Issue by BrainStone** [way2muchnoise/JustEnoughResources#90]
First of all I'm not entirely sure if this is just a dev env issue or not but I'm sadly not able to test it otherwise. (I used the deobf jar in the dev env for my mod)

As the title states all recipe pages are completly empty. Regardless of DIY mode or not.

Versions:
* Minecraft: 1.10.2
* Forge: 12.18.2.2123
* JEI:
  * 3.13.2.357
  * 3.13.2.360
* JER:
  * 1.10.2-0.5.4.71
  * 1.10.2-0.5.4.68
  * 1.9.4-0.4.6.39

I also get this stacktrace (only for 1.10.2 versions):

```
[04:01:13] [Client thread/INFO] [JEI]: Registering plugin: jeresources.jei.JEIConfig ...
[04:01:13] [Client thread/ERROR] [JEI]: Failed to register mod plugin: class jeresources.jei.JEIConfig
java.lang.NoSuchMethodError: net.minecraft.entity.monster.EntitySkeleton.setSkeletonType(Lnet/minecraft/entity/monster/SkeletonType;)V
	at jeresources.util.LootTableHelper.lambda$getAllMobLootTables$30(LootTableHelper.java:162) ~[LootTableHelper.class:?]
	at jeresources.util.MobTableBuilder.add(MobTableBuilder.java:28) ~[MobTableBuilder.class:?]
	at jeresources.util.LootTableHelper.getAllMobLootTables(LootTableHelper.java:162) ~[LootTableHelper.class:?]
	at jeresources.compatibility.minecraft.MinecraftCompat.registerVanillaMobs(MinecraftCompat.java:46) ~[MinecraftCompat.class:?]
	at jeresources.compatibility.minecraft.MinecraftCompat.init(MinecraftCompat.java:35) ~[MinecraftCompat.class:?]
	at jeresources.compatibility.Compatibility.init(Compatibility.java:20) ~[Compatibility.class:?]
	at jeresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:13) ~[CommonProxy.class:?]
	at jeresources.jei.JEIConfig.register(JEIConfig.java:43) ~[JEIConfig.class:?]
	at mezz.jei.JeiStarter.registerPlugins(JeiStarter.java:140) [JeiStarter.class:?]
	at mezz.jei.JeiStarter.start(JeiStarter.java:48) [JeiStarter.class:?]
	at mezz.jei.ProxyCommonClient.loadComplete(ProxyCommonClient.java:111) [ProxyCommonClient.class:?]
	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:53) [JustEnoughItems.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:602) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:803) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:561) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:386) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
```

**Comment by BrainStone** [comment]
Also when trying to register a mob manually I get this exception:

```
java.lang.IllegalAccessError: tried to access field net.minecraft.entity.EntityLiving.experienceValue from class jeresources.util.MobHelper
	at jeresources.util.MobHelper.getExpDrop(MobHelper.java:13) ~[JustEnoughResources-1.10.2-0.5.4.71-deobf.jar:?]
	at jeresources.entry.MobEntry.<init>(MobEntry.java:65) ~[JustEnoughResources-1.10.2-0.5.4.71-deobf.jar:?]
	at jeresources.entry.MobEntry.<init>(MobEntry.java:70) ~[JustEnoughResources-1.10.2-0.5.4.71-deobf.jar:?]
	at jeresources.compatibility.MobRegistryImpl.register(MobRegistryImpl.java:109) ~[JustEnoughResources-1.10.2-0.5.4.71-deobf.jar:?]
	at brainstonemod.common.api.jeresources.JEResourcesCompat.init(JEResourcesCompat.java:35) ~[bin/:?]
	at brainstonemod.common.api.BrainStoneModules.lambda$1(BrainStoneModules.java:168) ~[bin/:?]
	at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_111]
	at brainstonemod.common.api.BrainStoneModules.init(BrainStoneModules.java:168) ~[bin/:?]
	at brainstonemod.BrainStone.init(BrainStone.java:278) ~[bin/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:602) ~[forgeSrc-1.10.2-12.18.2.2123-PROJECT(Minecraft).jar:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239) ~[forgeSrc-1.10.2-12.18.2.2123-PROJECT(Minecraft).jar:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217) ~[forgeSrc-1.10.2-12.18.2.2123-PROJECT(Minecraft).jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:795) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:561) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:386) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
```

The strangest thing is when I use a deobf version of my mod and use it in your dev env it works.

**Comment by way2muchnoise** [comment]
Seems like it doesn't load the AT. How do you include it?

**Comment by BrainStone** [comment]
I just put the deobf jar in the libs folder and ran `gradlew eclipse`

**Comment by way2muchnoise** [comment]
So it is an import issue for sure. The first error is an issue with miss matching mcp data. You should at least match the version I use (or used for that build). The second is the AT, personally I don't use eclipse and use deobfCompile to just load in regular version instead of using deobf build as that is available now.

**Comment by BrainStone** [comment]
Hm. The first issue has appeared regardless of the version of the mapping (I tried the default in the MDK, your version and the most recent).  
And do I understand your suggestion correctly that I should try someting like this `deobfCompile file("libs/JustEnoughResources-1.10.2-0.5.4.71-deobf.jar")` in my build.gradle in the dependencies block?

**Comment by way2muchnoise** [comment]
yeah, but you don't need to use deobfCompile if you are using the deobf version ofc. I would say try the regular one with deobfCompile. And a method not existing seems rather odd for not being a mapping issue :/

**Comment by BrainStone** [comment]
Ok. It appears like running `gradlew setupDecompWorkspace` fixed the IllegalAccessError. But still empty pages...
If it helps you can hve a look at the repo: https://github.com/BrainStone/brainstone

**Comment by way2muchnoise** [comment]
I'm out of the country atm, so I won't be able to check it out till the weekend. But I'll get back to you then.

**Comment by BrainStone** [comment]
Ok. One more quick question: To add drops to an vanialla mob (I'm not usign loot tables because I handle the drop event fairly special) do I use `jerAPI.getMobRegistry().register(entity, lootDrop)`

**Comment by way2muchnoise** [comment]
It'll add an extra entry for the vanilla mob. I moved away from edits as you should really be using loottables to edit drops. Dunno what you are doing exactly, but it there is a ton of options with `EntityOptions` and `LootFuncitons`.

**Comment by BrainStone** [comment]
Ok. I need to rework that anyways so I will have a look at these anyways.

**Comment by BrainStone** [comment]
Well the crash with the IllegalAccessError did not go away. I simply made a mistake in my code and no longer called it. It is still there if I try to register a mob...

**Comment by BrainStone** [comment]
Ok. The IllegalAccessException went away but the NoSuchMethodError persits

**Comment by BrainStone** [comment]
Ok. Whatever. Now updating the mappings did work. I don't even want to start trying to understand why it didn't work the first time...
Thank you for your help anyways.
