### ISSUE TITLE
JER Errors out on loading

### ISSUE THREAD

**Issue by darkphan** [way2muchnoise/JustEnoughResources#91]
JER does not properly register on load, which causes it not to work in game:

I have tried various versions of JEI, JER and Forge, currently using:

JEI: jei_1.10.2-3.13.2.361
JER: JustEnoughResources-1.10.2-0.5.4.71
Forge: 12.18.2.2123

Log: 
[fml-client-latest.zip](https://github.com/way2muchnoise/JustEnoughResources/files/584542/fml-client-latest.zip)

[15:38:57] [Client thread/INFO] [JEI/JEI]: Registering plugin: jeresources.jei.JEIConfig ...
[15:38:57] [Client thread/ERROR] [JEI/JEI]: Failed to register mod plugin: class jeresources.jei.JEIConfig
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_25]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_25]
	at jeresources.collection.TradeList.addITradeList(TradeList.java:70) ~[TradeList.class:?]
	at jeresources.entry.VillagerEntry$$Lambda$1099/672394236.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_25]
	at jeresources.entry.VillagerEntry.addITradeLists(VillagerEntry.java:34) ~[VillagerEntry.class:?]
	at jeresources.entry.VillagerEntry.<init>(VillagerEntry.java:25) ~[VillagerEntry.class:?]
	at jeresources.util.VillagersHelper.initRegistry(VillagersHelper.java:22) ~[VillagersHelper.class:?]
	at jeresources.registry.VillagerRegistry.<init>(VillagerRegistry.java:25) ~[VillagerRegistry.class:?]
	at jeresources.registry.VillagerRegistry.getInstance(VillagerRegistry.java:18) ~[VillagerRegistry.class:?]
	at jeresources.jei.JEIConfig.register(JEIConfig.java:49) ~[JEIConfig.class:?]
	at mezz.jei.JeiStarter.registerPlugins(JeiStarter.java:140) [JeiStarter.class:?]
	at mezz.jei.JeiStarter.start(JeiStarter.java:48) [JeiStarter.class:?]
	at mezz.jei.ProxyCommonClient.loadComplete(ProxyCommonClient.java:111) [ProxyCommonClient.class:?]
	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:53) [JustEnoughItems.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:803) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[15:38:57] [Client thread/INFO] [JEI/JEI]: Registering plugin: forestry.arboriculture.compat.ArboricultureJeiPlugin ...
[15:38:57] [Client thread/INFO] [JEI/JEI]: Registered  plugin: forestry.arboriculture.compat.ArboricultureJeiPlugin in 0 ms

**Comment by darkphan** [comment]
Seems to be an issue between JER and Railcraft if you want to try to replicate it.
