### ISSUE TITLE
Console spammed with NPEs when you mouse over drops in the world gen gui

### ISSUE THREAD

**Issue by The-Fireplace** [way2muchnoise/JustEnoughResources#93]
When you look at the world gen gui, if you mouse over the block in the "Drops" section, the console is spammed with this:
java.lang.NullPointerException
	at java.util.ArrayList.<init>(ArrayList.java:177) ~[?:1.8.0_111]
	at jeresources.entry.WorldGenEntry.getLootDrops(WorldGenEntry.java:164) ~[WorldGenEntry.class:?]
	at jeresources.jei.worldgen.WorldGenWrapper.getItemStackTooltip(WorldGenWrapper.java:170) ~[WorldGenWrapper.class:?]
	at jeresources.jei.worldgen.WorldGenWrapper.onTooltip(WorldGenWrapper.java:141) ~[WorldGenWrapper.class:?]
	at jeresources.jei.worldgen.WorldGenWrapper.onTooltip(WorldGenWrapper.java:25) ~[WorldGenWrapper.class:?]
	at mezz.jei.gui.ingredients.GuiIngredient.drawTooltip(GuiIngredient.java:185) [GuiIngredient.class:?]
	at mezz.jei.gui.ingredients.GuiIngredient.drawHovered(GuiIngredient.java:156) [GuiIngredient.class:?]
	at mezz.jei.gui.recipes.RecipeLayout.draw(RecipeLayout.java:136) [RecipeLayout.class:?]
	at mezz.jei.gui.recipes.RecipesGui.drawScreen(RecipesGui.java:211) [RecipesGui.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1147) [EntityRenderer.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1139) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:406) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147) [idea_rt.jar:?]

**Comment by The-Fireplace** [comment]
It still does this for some custom recipes. Example: Stained Hardened Clay.
http://paste.ubuntu.com/23466477/
Added with the following code:
https://github.com/The-Fireplace/Fires-Clay-Spawn/blob/master/src/main/java/the_fireplace/clayspawn/compat/JERCompat.java#L31

If this is me doing something wrong, let me know.

**Comment by way2muchnoise** [comment]
I know it still happend in case of #95 something i'll be working on once mezz gets back to me about the oredict wildcard
